-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object exposing (..)


type AcceptEnterpriseAdministratorInvitationPayload
    = AcceptEnterpriseAdministratorInvitationPayload


type AcceptTopicSuggestionPayload
    = AcceptTopicSuggestionPayload


type ActorLocation
    = ActorLocation


type AddAssigneesToAssignablePayload
    = AddAssigneesToAssignablePayload


type AddCommentPayload
    = AddCommentPayload


type AddLabelsToLabelablePayload
    = AddLabelsToLabelablePayload


type AddProjectCardPayload
    = AddProjectCardPayload


type AddProjectColumnPayload
    = AddProjectColumnPayload


type AddPullRequestReviewCommentPayload
    = AddPullRequestReviewCommentPayload


type AddPullRequestReviewPayload
    = AddPullRequestReviewPayload


type AddPullRequestReviewThreadPayload
    = AddPullRequestReviewThreadPayload


type AddReactionPayload
    = AddReactionPayload


type AddStarPayload
    = AddStarPayload


type AddedToProjectEvent
    = AddedToProjectEvent


type App
    = App


type ArchiveRepositoryPayload
    = ArchiveRepositoryPayload


type AssignedEvent
    = AssignedEvent


type AutomaticBaseChangeFailedEvent
    = AutomaticBaseChangeFailedEvent


type AutomaticBaseChangeSucceededEvent
    = AutomaticBaseChangeSucceededEvent


type BaseRefChangedEvent
    = BaseRefChangedEvent


type BaseRefForcePushedEvent
    = BaseRefForcePushedEvent


type Blame
    = Blame


type BlameRange
    = BlameRange


type Blob
    = Blob


type Bot
    = Bot


type BranchProtectionRule
    = BranchProtectionRule


type BranchProtectionRuleConflict
    = BranchProtectionRuleConflict


type BranchProtectionRuleConflictConnection
    = BranchProtectionRuleConflictConnection


type BranchProtectionRuleConflictEdge
    = BranchProtectionRuleConflictEdge


type BranchProtectionRuleConnection
    = BranchProtectionRuleConnection


type BranchProtectionRuleEdge
    = BranchProtectionRuleEdge


type CancelEnterpriseAdminInvitationPayload
    = CancelEnterpriseAdminInvitationPayload


type ChangeUserStatusPayload
    = ChangeUserStatusPayload


type ClearLabelsFromLabelablePayload
    = ClearLabelsFromLabelablePayload


type CloneProjectPayload
    = CloneProjectPayload


type CloneTemplateRepositoryPayload
    = CloneTemplateRepositoryPayload


type CloseIssuePayload
    = CloseIssuePayload


type ClosePullRequestPayload
    = ClosePullRequestPayload


type ClosedEvent
    = ClosedEvent


type CodeOfConduct
    = CodeOfConduct


type CommentDeletedEvent
    = CommentDeletedEvent


type Commit
    = Commit


type CommitComment
    = CommitComment


type CommitCommentConnection
    = CommitCommentConnection


type CommitCommentEdge
    = CommitCommentEdge


type CommitCommentThread
    = CommitCommentThread


type CommitConnection
    = CommitConnection


type CommitContributionsByRepository
    = CommitContributionsByRepository


type CommitEdge
    = CommitEdge


type CommitHistoryConnection
    = CommitHistoryConnection


type ConnectedEvent
    = ConnectedEvent


type ContributionCalendar
    = ContributionCalendar


type ContributionCalendarDay
    = ContributionCalendarDay


type ContributionCalendarMonth
    = ContributionCalendarMonth


type ContributionCalendarWeek
    = ContributionCalendarWeek


type ContributionsCollection
    = ContributionsCollection


type ConvertProjectCardNoteToIssuePayload
    = ConvertProjectCardNoteToIssuePayload


type ConvertToDraftEvent
    = ConvertToDraftEvent


type ConvertedNoteToIssueEvent
    = ConvertedNoteToIssueEvent


type CreateBranchProtectionRulePayload
    = CreateBranchProtectionRulePayload


type CreateEnterpriseOrganizationPayload
    = CreateEnterpriseOrganizationPayload


type CreateIpAllowListEntryPayload
    = CreateIpAllowListEntryPayload


type CreateIssuePayload
    = CreateIssuePayload


type CreateProjectPayload
    = CreateProjectPayload


type CreatePullRequestPayload
    = CreatePullRequestPayload


type CreateRefPayload
    = CreateRefPayload


type CreateRepositoryPayload
    = CreateRepositoryPayload


type CreateTeamDiscussionCommentPayload
    = CreateTeamDiscussionCommentPayload


type CreateTeamDiscussionPayload
    = CreateTeamDiscussionPayload


type CreatedCommitContribution
    = CreatedCommitContribution


type CreatedCommitContributionConnection
    = CreatedCommitContributionConnection


type CreatedCommitContributionEdge
    = CreatedCommitContributionEdge


type CreatedIssueContribution
    = CreatedIssueContribution


type CreatedIssueContributionConnection
    = CreatedIssueContributionConnection


type CreatedIssueContributionEdge
    = CreatedIssueContributionEdge


type CreatedPullRequestContribution
    = CreatedPullRequestContribution


type CreatedPullRequestContributionConnection
    = CreatedPullRequestContributionConnection


type CreatedPullRequestContributionEdge
    = CreatedPullRequestContributionEdge


type CreatedPullRequestReviewContribution
    = CreatedPullRequestReviewContribution


type CreatedPullRequestReviewContributionConnection
    = CreatedPullRequestReviewContributionConnection


type CreatedPullRequestReviewContributionEdge
    = CreatedPullRequestReviewContributionEdge


type CreatedRepositoryContribution
    = CreatedRepositoryContribution


type CreatedRepositoryContributionConnection
    = CreatedRepositoryContributionConnection


type CreatedRepositoryContributionEdge
    = CreatedRepositoryContributionEdge


type CrossReferencedEvent
    = CrossReferencedEvent


type DeclineTopicSuggestionPayload
    = DeclineTopicSuggestionPayload


type DeleteBranchProtectionRulePayload
    = DeleteBranchProtectionRulePayload


type DeleteDeploymentPayload
    = DeleteDeploymentPayload


type DeleteIpAllowListEntryPayload
    = DeleteIpAllowListEntryPayload


type DeleteIssueCommentPayload
    = DeleteIssueCommentPayload


type DeleteIssuePayload
    = DeleteIssuePayload


type DeleteProjectCardPayload
    = DeleteProjectCardPayload


type DeleteProjectColumnPayload
    = DeleteProjectColumnPayload


type DeleteProjectPayload
    = DeleteProjectPayload


type DeletePullRequestReviewCommentPayload
    = DeletePullRequestReviewCommentPayload


type DeletePullRequestReviewPayload
    = DeletePullRequestReviewPayload


type DeleteRefPayload
    = DeleteRefPayload


type DeleteTeamDiscussionCommentPayload
    = DeleteTeamDiscussionCommentPayload


type DeleteTeamDiscussionPayload
    = DeleteTeamDiscussionPayload


type DemilestonedEvent
    = DemilestonedEvent


type DeployKey
    = DeployKey


type DeployKeyConnection
    = DeployKeyConnection


type DeployKeyEdge
    = DeployKeyEdge


type DeployedEvent
    = DeployedEvent


type Deployment
    = Deployment


type DeploymentConnection
    = DeploymentConnection


type DeploymentEdge
    = DeploymentEdge


type DeploymentEnvironmentChangedEvent
    = DeploymentEnvironmentChangedEvent


type DeploymentStatus
    = DeploymentStatus


type DeploymentStatusConnection
    = DeploymentStatusConnection


type DeploymentStatusEdge
    = DeploymentStatusEdge


type DisconnectedEvent
    = DisconnectedEvent


type DismissPullRequestReviewPayload
    = DismissPullRequestReviewPayload


type Enterprise
    = Enterprise


type EnterpriseAdministratorConnection
    = EnterpriseAdministratorConnection


type EnterpriseAdministratorEdge
    = EnterpriseAdministratorEdge


type EnterpriseAdministratorInvitation
    = EnterpriseAdministratorInvitation


type EnterpriseAdministratorInvitationConnection
    = EnterpriseAdministratorInvitationConnection


type EnterpriseAdministratorInvitationEdge
    = EnterpriseAdministratorInvitationEdge


type EnterpriseBillingInfo
    = EnterpriseBillingInfo


type EnterpriseIdentityProvider
    = EnterpriseIdentityProvider


type EnterpriseMemberConnection
    = EnterpriseMemberConnection


type EnterpriseMemberEdge
    = EnterpriseMemberEdge


type EnterpriseOrganizationMembershipConnection
    = EnterpriseOrganizationMembershipConnection


type EnterpriseOrganizationMembershipEdge
    = EnterpriseOrganizationMembershipEdge


type EnterpriseOutsideCollaboratorConnection
    = EnterpriseOutsideCollaboratorConnection


type EnterpriseOutsideCollaboratorEdge
    = EnterpriseOutsideCollaboratorEdge


type EnterpriseOwnerInfo
    = EnterpriseOwnerInfo


type EnterprisePendingCollaboratorConnection
    = EnterprisePendingCollaboratorConnection


type EnterprisePendingCollaboratorEdge
    = EnterprisePendingCollaboratorEdge


type EnterprisePendingMemberInvitationConnection
    = EnterprisePendingMemberInvitationConnection


type EnterprisePendingMemberInvitationEdge
    = EnterprisePendingMemberInvitationEdge


type EnterpriseRepositoryInfo
    = EnterpriseRepositoryInfo


type EnterpriseRepositoryInfoConnection
    = EnterpriseRepositoryInfoConnection


type EnterpriseRepositoryInfoEdge
    = EnterpriseRepositoryInfoEdge


type EnterpriseServerInstallation
    = EnterpriseServerInstallation


type EnterpriseServerInstallationConnection
    = EnterpriseServerInstallationConnection


type EnterpriseServerInstallationEdge
    = EnterpriseServerInstallationEdge


type EnterpriseServerUserAccount
    = EnterpriseServerUserAccount


type EnterpriseServerUserAccountConnection
    = EnterpriseServerUserAccountConnection


type EnterpriseServerUserAccountEdge
    = EnterpriseServerUserAccountEdge


type EnterpriseServerUserAccountEmail
    = EnterpriseServerUserAccountEmail


type EnterpriseServerUserAccountEmailConnection
    = EnterpriseServerUserAccountEmailConnection


type EnterpriseServerUserAccountEmailEdge
    = EnterpriseServerUserAccountEmailEdge


type EnterpriseServerUserAccountsUpload
    = EnterpriseServerUserAccountsUpload


type EnterpriseServerUserAccountsUploadConnection
    = EnterpriseServerUserAccountsUploadConnection


type EnterpriseServerUserAccountsUploadEdge
    = EnterpriseServerUserAccountsUploadEdge


type EnterpriseUserAccount
    = EnterpriseUserAccount


type EnterpriseUserAccountConnection
    = EnterpriseUserAccountConnection


type EnterpriseUserAccountEdge
    = EnterpriseUserAccountEdge


type ExternalIdentity
    = ExternalIdentity


type ExternalIdentityConnection
    = ExternalIdentityConnection


type ExternalIdentityEdge
    = ExternalIdentityEdge


type ExternalIdentitySamlAttributes
    = ExternalIdentitySamlAttributes


type ExternalIdentityScimAttributes
    = ExternalIdentityScimAttributes


type FollowUserPayload
    = FollowUserPayload


type FollowerConnection
    = FollowerConnection


type FollowingConnection
    = FollowingConnection


type FundingLink
    = FundingLink


type GenericHovercardContext
    = GenericHovercardContext


type Gist
    = Gist


type GistComment
    = GistComment


type GistCommentConnection
    = GistCommentConnection


type GistCommentEdge
    = GistCommentEdge


type GistConnection
    = GistConnection


type GistEdge
    = GistEdge


type GistFile
    = GistFile


type GitActor
    = GitActor


type GitHubMetadata
    = GitHubMetadata


type GpgSignature
    = GpgSignature


type HeadRefDeletedEvent
    = HeadRefDeletedEvent


type HeadRefForcePushedEvent
    = HeadRefForcePushedEvent


type HeadRefRestoredEvent
    = HeadRefRestoredEvent


type Hovercard
    = Hovercard


type InviteEnterpriseAdminPayload
    = InviteEnterpriseAdminPayload


type IpAllowListEntry
    = IpAllowListEntry


type IpAllowListEntryConnection
    = IpAllowListEntryConnection


type IpAllowListEntryEdge
    = IpAllowListEntryEdge


type Issue
    = Issue


type IssueComment
    = IssueComment


type IssueCommentConnection
    = IssueCommentConnection


type IssueCommentEdge
    = IssueCommentEdge


type IssueConnection
    = IssueConnection


type IssueContributionsByRepository
    = IssueContributionsByRepository


type IssueEdge
    = IssueEdge


type IssueTimelineConnection
    = IssueTimelineConnection


type IssueTimelineItemEdge
    = IssueTimelineItemEdge


type IssueTimelineItemsConnection
    = IssueTimelineItemsConnection


type IssueTimelineItemsEdge
    = IssueTimelineItemsEdge


type JoinedGitHubContribution
    = JoinedGitHubContribution


type Label
    = Label


type LabelConnection
    = LabelConnection


type LabelEdge
    = LabelEdge


type LabeledEvent
    = LabeledEvent


type Language
    = Language


type LanguageConnection
    = LanguageConnection


type LanguageEdge
    = LanguageEdge


type License
    = License


type LicenseRule
    = LicenseRule


type LinkRepositoryToProjectPayload
    = LinkRepositoryToProjectPayload


type LockLockablePayload
    = LockLockablePayload


type LockedEvent
    = LockedEvent


type Mannequin
    = Mannequin


type MarkPullRequestReadyForReviewPayload
    = MarkPullRequestReadyForReviewPayload


type MarkedAsDuplicateEvent
    = MarkedAsDuplicateEvent


type MarketplaceCategory
    = MarketplaceCategory


type MarketplaceListing
    = MarketplaceListing


type MarketplaceListingConnection
    = MarketplaceListingConnection


type MarketplaceListingEdge
    = MarketplaceListingEdge


type MembersCanDeleteReposClearAuditEntry
    = MembersCanDeleteReposClearAuditEntry


type MembersCanDeleteReposDisableAuditEntry
    = MembersCanDeleteReposDisableAuditEntry


type MembersCanDeleteReposEnableAuditEntry
    = MembersCanDeleteReposEnableAuditEntry


type MentionedEvent
    = MentionedEvent


type MergeBranchPayload
    = MergeBranchPayload


type MergePullRequestPayload
    = MergePullRequestPayload


type MergedEvent
    = MergedEvent


type Milestone
    = Milestone


type MilestoneConnection
    = MilestoneConnection


type MilestoneEdge
    = MilestoneEdge


type MilestonedEvent
    = MilestonedEvent


type MinimizeCommentPayload
    = MinimizeCommentPayload


type MoveProjectCardPayload
    = MoveProjectCardPayload


type MoveProjectColumnPayload
    = MoveProjectColumnPayload


type MovedColumnsInProjectEvent
    = MovedColumnsInProjectEvent


type OauthApplicationCreateAuditEntry
    = OauthApplicationCreateAuditEntry


type OrgAddBillingManagerAuditEntry
    = OrgAddBillingManagerAuditEntry


type OrgAddMemberAuditEntry
    = OrgAddMemberAuditEntry


type OrgBlockUserAuditEntry
    = OrgBlockUserAuditEntry


type OrgConfigDisableCollaboratorsOnlyAuditEntry
    = OrgConfigDisableCollaboratorsOnlyAuditEntry


type OrgConfigEnableCollaboratorsOnlyAuditEntry
    = OrgConfigEnableCollaboratorsOnlyAuditEntry


type OrgCreateAuditEntry
    = OrgCreateAuditEntry


type OrgDisableOauthAppRestrictionsAuditEntry
    = OrgDisableOauthAppRestrictionsAuditEntry


type OrgDisableSamlAuditEntry
    = OrgDisableSamlAuditEntry


type OrgDisableTwoFactorRequirementAuditEntry
    = OrgDisableTwoFactorRequirementAuditEntry


type OrgEnableOauthAppRestrictionsAuditEntry
    = OrgEnableOauthAppRestrictionsAuditEntry


type OrgEnableSamlAuditEntry
    = OrgEnableSamlAuditEntry


type OrgEnableTwoFactorRequirementAuditEntry
    = OrgEnableTwoFactorRequirementAuditEntry


type OrgInviteMemberAuditEntry
    = OrgInviteMemberAuditEntry


type OrgInviteToBusinessAuditEntry
    = OrgInviteToBusinessAuditEntry


type OrgOauthAppAccessApprovedAuditEntry
    = OrgOauthAppAccessApprovedAuditEntry


type OrgOauthAppAccessDeniedAuditEntry
    = OrgOauthAppAccessDeniedAuditEntry


type OrgOauthAppAccessRequestedAuditEntry
    = OrgOauthAppAccessRequestedAuditEntry


type OrgRemoveBillingManagerAuditEntry
    = OrgRemoveBillingManagerAuditEntry


type OrgRemoveMemberAuditEntry
    = OrgRemoveMemberAuditEntry


type OrgRemoveOutsideCollaboratorAuditEntry
    = OrgRemoveOutsideCollaboratorAuditEntry


type OrgRestoreMemberAuditEntry
    = OrgRestoreMemberAuditEntry


type OrgRestoreMemberMembershipOrganizationAuditEntryData
    = OrgRestoreMemberMembershipOrganizationAuditEntryData


type OrgRestoreMemberMembershipRepositoryAuditEntryData
    = OrgRestoreMemberMembershipRepositoryAuditEntryData


type OrgRestoreMemberMembershipTeamAuditEntryData
    = OrgRestoreMemberMembershipTeamAuditEntryData


type OrgUnblockUserAuditEntry
    = OrgUnblockUserAuditEntry


type OrgUpdateDefaultRepositoryPermissionAuditEntry
    = OrgUpdateDefaultRepositoryPermissionAuditEntry


type OrgUpdateMemberAuditEntry
    = OrgUpdateMemberAuditEntry


type OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    = OrgUpdateMemberRepositoryCreationPermissionAuditEntry


type OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    = OrgUpdateMemberRepositoryInvitationPermissionAuditEntry


type Organization
    = Organization


type OrganizationAuditEntryConnection
    = OrganizationAuditEntryConnection


type OrganizationAuditEntryEdge
    = OrganizationAuditEntryEdge


type OrganizationConnection
    = OrganizationConnection


type OrganizationEdge
    = OrganizationEdge


type OrganizationIdentityProvider
    = OrganizationIdentityProvider


type OrganizationInvitation
    = OrganizationInvitation


type OrganizationInvitationConnection
    = OrganizationInvitationConnection


type OrganizationInvitationEdge
    = OrganizationInvitationEdge


type OrganizationMemberConnection
    = OrganizationMemberConnection


type OrganizationMemberEdge
    = OrganizationMemberEdge


type OrganizationTeamsHovercardContext
    = OrganizationTeamsHovercardContext


type OrganizationsHovercardContext
    = OrganizationsHovercardContext


type PageInfo
    = PageInfo


type PermissionSource
    = PermissionSource


type PinnableItemConnection
    = PinnableItemConnection


type PinnableItemEdge
    = PinnableItemEdge


type PinnedEvent
    = PinnedEvent


type PrivateRepositoryForkingDisableAuditEntry
    = PrivateRepositoryForkingDisableAuditEntry


type PrivateRepositoryForkingEnableAuditEntry
    = PrivateRepositoryForkingEnableAuditEntry


type ProfileItemShowcase
    = ProfileItemShowcase


type Project
    = Project


type ProjectCard
    = ProjectCard


type ProjectCardConnection
    = ProjectCardConnection


type ProjectCardEdge
    = ProjectCardEdge


type ProjectColumn
    = ProjectColumn


type ProjectColumnConnection
    = ProjectColumnConnection


type ProjectColumnEdge
    = ProjectColumnEdge


type ProjectConnection
    = ProjectConnection


type ProjectEdge
    = ProjectEdge


type PublicKey
    = PublicKey


type PublicKeyConnection
    = PublicKeyConnection


type PublicKeyEdge
    = PublicKeyEdge


type PullRequest
    = PullRequest


type PullRequestChangedFile
    = PullRequestChangedFile


type PullRequestChangedFileConnection
    = PullRequestChangedFileConnection


type PullRequestChangedFileEdge
    = PullRequestChangedFileEdge


type PullRequestCommit
    = PullRequestCommit


type PullRequestCommitCommentThread
    = PullRequestCommitCommentThread


type PullRequestCommitConnection
    = PullRequestCommitConnection


type PullRequestCommitEdge
    = PullRequestCommitEdge


type PullRequestConnection
    = PullRequestConnection


type PullRequestContributionsByRepository
    = PullRequestContributionsByRepository


type PullRequestEdge
    = PullRequestEdge


type PullRequestReview
    = PullRequestReview


type PullRequestReviewComment
    = PullRequestReviewComment


type PullRequestReviewCommentConnection
    = PullRequestReviewCommentConnection


type PullRequestReviewCommentEdge
    = PullRequestReviewCommentEdge


type PullRequestReviewConnection
    = PullRequestReviewConnection


type PullRequestReviewContributionsByRepository
    = PullRequestReviewContributionsByRepository


type PullRequestReviewEdge
    = PullRequestReviewEdge


type PullRequestReviewThread
    = PullRequestReviewThread


type PullRequestReviewThreadConnection
    = PullRequestReviewThreadConnection


type PullRequestReviewThreadEdge
    = PullRequestReviewThreadEdge


type PullRequestRevisionMarker
    = PullRequestRevisionMarker


type PullRequestTimelineConnection
    = PullRequestTimelineConnection


type PullRequestTimelineItemEdge
    = PullRequestTimelineItemEdge


type PullRequestTimelineItemsConnection
    = PullRequestTimelineItemsConnection


type PullRequestTimelineItemsEdge
    = PullRequestTimelineItemsEdge


type PushAllowance
    = PushAllowance


type PushAllowanceConnection
    = PushAllowanceConnection


type PushAllowanceEdge
    = PushAllowanceEdge


type RateLimit
    = RateLimit


type ReactingUserConnection
    = ReactingUserConnection


type ReactingUserEdge
    = ReactingUserEdge


type Reaction
    = Reaction


type ReactionConnection
    = ReactionConnection


type ReactionEdge
    = ReactionEdge


type ReactionGroup
    = ReactionGroup


type ReadyForReviewEvent
    = ReadyForReviewEvent


type Ref
    = Ref


type RefConnection
    = RefConnection


type RefEdge
    = RefEdge


type ReferencedEvent
    = ReferencedEvent


type RegenerateEnterpriseIdentityProviderRecoveryCodesPayload
    = RegenerateEnterpriseIdentityProviderRecoveryCodesPayload


type RegistryPackage
    = RegistryPackage


type RegistryPackageConnection
    = RegistryPackageConnection


type RegistryPackageDependency
    = RegistryPackageDependency


type RegistryPackageDependencyConnection
    = RegistryPackageDependencyConnection


type RegistryPackageDependencyEdge
    = RegistryPackageDependencyEdge


type RegistryPackageEdge
    = RegistryPackageEdge


type RegistryPackageFile
    = RegistryPackageFile


type RegistryPackageFileConnection
    = RegistryPackageFileConnection


type RegistryPackageFileEdge
    = RegistryPackageFileEdge


type RegistryPackageStatistics
    = RegistryPackageStatistics


type RegistryPackageTag
    = RegistryPackageTag


type RegistryPackageTagConnection
    = RegistryPackageTagConnection


type RegistryPackageTagEdge
    = RegistryPackageTagEdge


type RegistryPackageVersion
    = RegistryPackageVersion


type RegistryPackageVersionConnection
    = RegistryPackageVersionConnection


type RegistryPackageVersionEdge
    = RegistryPackageVersionEdge


type RegistryPackageVersionStatistics
    = RegistryPackageVersionStatistics


type Release
    = Release


type ReleaseAsset
    = ReleaseAsset


type ReleaseAssetConnection
    = ReleaseAssetConnection


type ReleaseAssetEdge
    = ReleaseAssetEdge


type ReleaseConnection
    = ReleaseConnection


type ReleaseEdge
    = ReleaseEdge


type RemoveAssigneesFromAssignablePayload
    = RemoveAssigneesFromAssignablePayload


type RemoveEnterpriseAdminPayload
    = RemoveEnterpriseAdminPayload


type RemoveEnterpriseIdentityProviderPayload
    = RemoveEnterpriseIdentityProviderPayload


type RemoveEnterpriseOrganizationPayload
    = RemoveEnterpriseOrganizationPayload


type RemoveLabelsFromLabelablePayload
    = RemoveLabelsFromLabelablePayload


type RemoveOutsideCollaboratorPayload
    = RemoveOutsideCollaboratorPayload


type RemoveReactionPayload
    = RemoveReactionPayload


type RemoveStarPayload
    = RemoveStarPayload


type RemovedFromProjectEvent
    = RemovedFromProjectEvent


type RenamedTitleEvent
    = RenamedTitleEvent


type ReopenIssuePayload
    = ReopenIssuePayload


type ReopenPullRequestPayload
    = ReopenPullRequestPayload


type ReopenedEvent
    = ReopenedEvent


type RepoAccessAuditEntry
    = RepoAccessAuditEntry


type RepoAddMemberAuditEntry
    = RepoAddMemberAuditEntry


type RepoAddTopicAuditEntry
    = RepoAddTopicAuditEntry


type RepoArchivedAuditEntry
    = RepoArchivedAuditEntry


type RepoChangeMergeSettingAuditEntry
    = RepoChangeMergeSettingAuditEntry


type RepoConfigDisableAnonymousGitAccessAuditEntry
    = RepoConfigDisableAnonymousGitAccessAuditEntry


type RepoConfigDisableCollaboratorsOnlyAuditEntry
    = RepoConfigDisableCollaboratorsOnlyAuditEntry


type RepoConfigDisableContributorsOnlyAuditEntry
    = RepoConfigDisableContributorsOnlyAuditEntry


type RepoConfigDisableSockpuppetDisallowedAuditEntry
    = RepoConfigDisableSockpuppetDisallowedAuditEntry


type RepoConfigEnableAnonymousGitAccessAuditEntry
    = RepoConfigEnableAnonymousGitAccessAuditEntry


type RepoConfigEnableCollaboratorsOnlyAuditEntry
    = RepoConfigEnableCollaboratorsOnlyAuditEntry


type RepoConfigEnableContributorsOnlyAuditEntry
    = RepoConfigEnableContributorsOnlyAuditEntry


type RepoConfigEnableSockpuppetDisallowedAuditEntry
    = RepoConfigEnableSockpuppetDisallowedAuditEntry


type RepoConfigLockAnonymousGitAccessAuditEntry
    = RepoConfigLockAnonymousGitAccessAuditEntry


type RepoConfigUnlockAnonymousGitAccessAuditEntry
    = RepoConfigUnlockAnonymousGitAccessAuditEntry


type RepoCreateAuditEntry
    = RepoCreateAuditEntry


type RepoDestroyAuditEntry
    = RepoDestroyAuditEntry


type RepoRemoveMemberAuditEntry
    = RepoRemoveMemberAuditEntry


type RepoRemoveTopicAuditEntry
    = RepoRemoveTopicAuditEntry


type Repository
    = Repository


type RepositoryCollaboratorConnection
    = RepositoryCollaboratorConnection


type RepositoryCollaboratorEdge
    = RepositoryCollaboratorEdge


type RepositoryConnection
    = RepositoryConnection


type RepositoryEdge
    = RepositoryEdge


type RepositoryInvitation
    = RepositoryInvitation


type RepositoryInvitationConnection
    = RepositoryInvitationConnection


type RepositoryInvitationEdge
    = RepositoryInvitationEdge


type RepositoryTopic
    = RepositoryTopic


type RepositoryTopicConnection
    = RepositoryTopicConnection


type RepositoryTopicEdge
    = RepositoryTopicEdge


type RepositoryVisibilityChangeDisableAuditEntry
    = RepositoryVisibilityChangeDisableAuditEntry


type RepositoryVisibilityChangeEnableAuditEntry
    = RepositoryVisibilityChangeEnableAuditEntry


type RepositoryVulnerabilityAlert
    = RepositoryVulnerabilityAlert


type RepositoryVulnerabilityAlertConnection
    = RepositoryVulnerabilityAlertConnection


type RepositoryVulnerabilityAlertEdge
    = RepositoryVulnerabilityAlertEdge


type RequestReviewsPayload
    = RequestReviewsPayload


type ResolveReviewThreadPayload
    = ResolveReviewThreadPayload


type RestrictedContribution
    = RestrictedContribution


type ReviewDismissalAllowance
    = ReviewDismissalAllowance


type ReviewDismissalAllowanceConnection
    = ReviewDismissalAllowanceConnection


type ReviewDismissalAllowanceEdge
    = ReviewDismissalAllowanceEdge


type ReviewDismissedEvent
    = ReviewDismissedEvent


type ReviewRequest
    = ReviewRequest


type ReviewRequestConnection
    = ReviewRequestConnection


type ReviewRequestEdge
    = ReviewRequestEdge


type ReviewRequestRemovedEvent
    = ReviewRequestRemovedEvent


type ReviewRequestedEvent
    = ReviewRequestedEvent


type ReviewStatusHovercardContext
    = ReviewStatusHovercardContext


type SavedReply
    = SavedReply


type SavedReplyConnection
    = SavedReplyConnection


type SavedReplyEdge
    = SavedReplyEdge


type SearchResultItemConnection
    = SearchResultItemConnection


type SearchResultItemEdge
    = SearchResultItemEdge


type SecurityAdvisory
    = SecurityAdvisory


type SecurityAdvisoryConnection
    = SecurityAdvisoryConnection


type SecurityAdvisoryEdge
    = SecurityAdvisoryEdge


type SecurityAdvisoryIdentifier
    = SecurityAdvisoryIdentifier


type SecurityAdvisoryPackage
    = SecurityAdvisoryPackage


type SecurityAdvisoryPackageVersion
    = SecurityAdvisoryPackageVersion


type SecurityAdvisoryReference
    = SecurityAdvisoryReference


type SecurityVulnerability
    = SecurityVulnerability


type SecurityVulnerabilityConnection
    = SecurityVulnerabilityConnection


type SecurityVulnerabilityEdge
    = SecurityVulnerabilityEdge


type SetEnterpriseIdentityProviderPayload
    = SetEnterpriseIdentityProviderPayload


type SmimeSignature
    = SmimeSignature


type SponsorsListing
    = SponsorsListing


type SponsorsTier
    = SponsorsTier


type SponsorsTierAdminInfo
    = SponsorsTierAdminInfo


type SponsorsTierConnection
    = SponsorsTierConnection


type SponsorsTierEdge
    = SponsorsTierEdge


type Sponsorship
    = Sponsorship


type SponsorshipConnection
    = SponsorshipConnection


type SponsorshipEdge
    = SponsorshipEdge


type StargazerConnection
    = StargazerConnection


type StargazerEdge
    = StargazerEdge


type StarredRepositoryConnection
    = StarredRepositoryConnection


type StarredRepositoryEdge
    = StarredRepositoryEdge


type Status
    = Status


type StatusCheckRollup
    = StatusCheckRollup


type StatusCheckRollupContextConnection
    = StatusCheckRollupContextConnection


type StatusCheckRollupContextEdge
    = StatusCheckRollupContextEdge


type StatusContext
    = StatusContext


type SubmitPullRequestReviewPayload
    = SubmitPullRequestReviewPayload


type Submodule
    = Submodule


type SubmoduleConnection
    = SubmoduleConnection


type SubmoduleEdge
    = SubmoduleEdge


type SubscribedEvent
    = SubscribedEvent


type SuggestedReviewer
    = SuggestedReviewer


type Tag
    = Tag


type Team
    = Team


type TeamAddMemberAuditEntry
    = TeamAddMemberAuditEntry


type TeamAddRepositoryAuditEntry
    = TeamAddRepositoryAuditEntry


type TeamChangeParentTeamAuditEntry
    = TeamChangeParentTeamAuditEntry


type TeamConnection
    = TeamConnection


type TeamDiscussion
    = TeamDiscussion


type TeamDiscussionComment
    = TeamDiscussionComment


type TeamDiscussionCommentConnection
    = TeamDiscussionCommentConnection


type TeamDiscussionCommentEdge
    = TeamDiscussionCommentEdge


type TeamDiscussionConnection
    = TeamDiscussionConnection


type TeamDiscussionEdge
    = TeamDiscussionEdge


type TeamEdge
    = TeamEdge


type TeamMemberConnection
    = TeamMemberConnection


type TeamMemberEdge
    = TeamMemberEdge


type TeamRemoveMemberAuditEntry
    = TeamRemoveMemberAuditEntry


type TeamRemoveRepositoryAuditEntry
    = TeamRemoveRepositoryAuditEntry


type TeamRepositoryConnection
    = TeamRepositoryConnection


type TeamRepositoryEdge
    = TeamRepositoryEdge


type TextMatch
    = TextMatch


type TextMatchHighlight
    = TextMatchHighlight


type Topic
    = Topic


type TopicConnection
    = TopicConnection


type TopicEdge
    = TopicEdge


type TransferIssuePayload
    = TransferIssuePayload


type TransferredEvent
    = TransferredEvent


type Tree
    = Tree


type TreeEntry
    = TreeEntry


type UnarchiveRepositoryPayload
    = UnarchiveRepositoryPayload


type UnassignedEvent
    = UnassignedEvent


type UnfollowUserPayload
    = UnfollowUserPayload


type UnknownSignature
    = UnknownSignature


type UnlabeledEvent
    = UnlabeledEvent


type UnlinkRepositoryFromProjectPayload
    = UnlinkRepositoryFromProjectPayload


type UnlockLockablePayload
    = UnlockLockablePayload


type UnlockedEvent
    = UnlockedEvent


type UnmarkIssueAsDuplicatePayload
    = UnmarkIssueAsDuplicatePayload


type UnmarkedAsDuplicateEvent
    = UnmarkedAsDuplicateEvent


type UnminimizeCommentPayload
    = UnminimizeCommentPayload


type UnpinnedEvent
    = UnpinnedEvent


type UnresolveReviewThreadPayload
    = UnresolveReviewThreadPayload


type UnsubscribedEvent
    = UnsubscribedEvent


type UpdateBranchProtectionRulePayload
    = UpdateBranchProtectionRulePayload


type UpdateEnterpriseActionExecutionCapabilitySettingPayload
    = UpdateEnterpriseActionExecutionCapabilitySettingPayload


type UpdateEnterpriseAdministratorRolePayload
    = UpdateEnterpriseAdministratorRolePayload


type UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload
    = UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload


type UpdateEnterpriseDefaultRepositoryPermissionSettingPayload
    = UpdateEnterpriseDefaultRepositoryPermissionSettingPayload


type UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload
    = UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload


type UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload
    = UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload


type UpdateEnterpriseMembersCanDeleteIssuesSettingPayload
    = UpdateEnterpriseMembersCanDeleteIssuesSettingPayload


type UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload
    = UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload


type UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload
    = UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload


type UpdateEnterpriseMembersCanMakePurchasesSettingPayload
    = UpdateEnterpriseMembersCanMakePurchasesSettingPayload


type UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload
    = UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload


type UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload
    = UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload


type UpdateEnterpriseOrganizationProjectsSettingPayload
    = UpdateEnterpriseOrganizationProjectsSettingPayload


type UpdateEnterpriseProfilePayload
    = UpdateEnterpriseProfilePayload


type UpdateEnterpriseRepositoryProjectsSettingPayload
    = UpdateEnterpriseRepositoryProjectsSettingPayload


type UpdateEnterpriseTeamDiscussionsSettingPayload
    = UpdateEnterpriseTeamDiscussionsSettingPayload


type UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload
    = UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload


type UpdateIpAllowListEnabledSettingPayload
    = UpdateIpAllowListEnabledSettingPayload


type UpdateIpAllowListEntryPayload
    = UpdateIpAllowListEntryPayload


type UpdateIssueCommentPayload
    = UpdateIssueCommentPayload


type UpdateIssuePayload
    = UpdateIssuePayload


type UpdateProjectCardPayload
    = UpdateProjectCardPayload


type UpdateProjectColumnPayload
    = UpdateProjectColumnPayload


type UpdateProjectPayload
    = UpdateProjectPayload


type UpdatePullRequestPayload
    = UpdatePullRequestPayload


type UpdatePullRequestReviewCommentPayload
    = UpdatePullRequestReviewCommentPayload


type UpdatePullRequestReviewPayload
    = UpdatePullRequestReviewPayload


type UpdateRefPayload
    = UpdateRefPayload


type UpdateRepositoryPayload
    = UpdateRepositoryPayload


type UpdateSubscriptionPayload
    = UpdateSubscriptionPayload


type UpdateTeamDiscussionCommentPayload
    = UpdateTeamDiscussionCommentPayload


type UpdateTeamDiscussionPayload
    = UpdateTeamDiscussionPayload


type UpdateTopicsPayload
    = UpdateTopicsPayload


type User
    = User


type UserBlockedEvent
    = UserBlockedEvent


type UserConnection
    = UserConnection


type UserContentEdit
    = UserContentEdit


type UserContentEditConnection
    = UserContentEditConnection


type UserContentEditEdge
    = UserContentEditEdge


type UserEdge
    = UserEdge


type UserStatus
    = UserStatus


type UserStatusConnection
    = UserStatusConnection


type UserStatusEdge
    = UserStatusEdge


type ViewerHovercardContext
    = ViewerHovercardContext
