-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.EnterpriseAdministratorEdge exposing (..)

import GitHub.Enum.EnterpriseAdministratorRole
import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A cursor for use in pagination.
-}
cursor : SelectionSet String GitHub.Object.EnterpriseAdministratorEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string


{-| The item at the end of the edge.
-}
node :
    SelectionSet decodesTo GitHub.Object.User
    -> SelectionSet (Maybe decodesTo) GitHub.Object.EnterpriseAdministratorEdge
node object_ =
    Object.selectionForCompositeField "node" [] object_ (identity >> Decode.nullable)


{-| The role of the administrator.
-}
role : SelectionSet GitHub.Enum.EnterpriseAdministratorRole.EnterpriseAdministratorRole GitHub.Object.EnterpriseAdministratorEdge
role =
    Object.selectionForField "Enum.EnterpriseAdministratorRole.EnterpriseAdministratorRole" "role" [] GitHub.Enum.EnterpriseAdministratorRole.decoder
