-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.EnterpriseServerUserAccount exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet GitHub.ScalarCodecs.DateTime GitHub.Object.EnterpriseServerUserAccount
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


type alias EmailsOptionalArguments =
    { orderBy : OptionalArgument GitHub.InputObject.EnterpriseServerUserAccountEmailOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| User emails belonging to this user account.

  - orderBy - Ordering options for Enterprise Server user account emails returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
emails : (EmailsOptionalArguments -> EmailsOptionalArguments) -> SelectionSet decodesTo GitHub.Object.EnterpriseServerUserAccountEmailConnection -> SelectionSet decodesTo GitHub.Object.EnterpriseServerUserAccount
emails fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "orderBy" filledInOptionals.orderBy GitHub.InputObject.encodeEnterpriseServerUserAccountEmailOrder, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "emails" optionalArgs object_ identity


{-| The Enterprise Server installation on which this user account exists.
-}
enterpriseServerInstallation : SelectionSet decodesTo GitHub.Object.EnterpriseServerInstallation -> SelectionSet decodesTo GitHub.Object.EnterpriseServerUserAccount
enterpriseServerInstallation object_ =
    Object.selectionForCompositeField "enterpriseServerInstallation" [] object_ identity


id : SelectionSet GitHub.ScalarCodecs.Id GitHub.Object.EnterpriseServerUserAccount
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether the user account is a site administrator on the Enterprise Server installation.
-}
isSiteAdmin : SelectionSet Bool GitHub.Object.EnterpriseServerUserAccount
isSiteAdmin =
    Object.selectionForField "Bool" "isSiteAdmin" [] Decode.bool


{-| The login of the user account on the Enterprise Server installation.
-}
login : SelectionSet String GitHub.Object.EnterpriseServerUserAccount
login =
    Object.selectionForField "String" "login" [] Decode.string


{-| The profile name of the user account on the Enterprise Server installation.
-}
profileName : SelectionSet (Maybe String) GitHub.Object.EnterpriseServerUserAccount
profileName =
    Object.selectionForField "(Maybe String)" "profileName" [] (Decode.string |> Decode.nullable)


{-| The date and time when the user account was created on the Enterprise Server installation.
-}
remoteCreatedAt : SelectionSet GitHub.ScalarCodecs.DateTime GitHub.Object.EnterpriseServerUserAccount
remoteCreatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "remoteCreatedAt" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The ID of the user account on the Enterprise Server installation.
-}
remoteUserId : SelectionSet Int GitHub.Object.EnterpriseServerUserAccount
remoteUserId =
    Object.selectionForField "Int" "remoteUserId" [] Decode.int


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet GitHub.ScalarCodecs.DateTime GitHub.Object.EnterpriseServerUserAccount
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
