-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.IpAllowListEntry exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A single IP address or range of IP addresses in CIDR notation.
-}
allowListValue : SelectionSet String GitHub.Object.IpAllowListEntry
allowListValue =
    Object.selectionForField "String" "allowListValue" [] Decode.string


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet GitHub.ScalarCodecs.DateTime GitHub.Object.IpAllowListEntry
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


id : SelectionSet GitHub.ScalarCodecs.Id GitHub.Object.IpAllowListEntry
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether the entry is currently active.
-}
isActive : SelectionSet Bool GitHub.Object.IpAllowListEntry
isActive =
    Object.selectionForField "Bool" "isActive" [] Decode.bool


{-| The name of the IP allow list entry.
-}
name : SelectionSet (Maybe String) GitHub.Object.IpAllowListEntry
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The owner of the IP allow list entry.
-}
owner :
    SelectionSet decodesTo GitHub.Union.IpAllowListOwner
    -> SelectionSet decodesTo GitHub.Object.IpAllowListEntry
owner object_ =
    Object.selectionForCompositeField "owner" [] object_ identity


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet GitHub.ScalarCodecs.DateTime GitHub.Object.IpAllowListEntry
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
