-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The team associated with the action
-}
team : SelectionSet decodesTo GitHub.Object.Team -> SelectionSet (Maybe decodesTo) GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData
team object_ =
    Object.selectionForCompositeField "team" [] object_ (identity >> Decode.nullable)


{-| The name of the team
-}
teamName : SelectionSet (Maybe String) GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData
teamName =
    Object.selectionForField "(Maybe String)" "teamName" [] (Decode.string |> Decode.nullable)


{-| The HTTP path for this team
-}
teamResourcePath : SelectionSet (Maybe GitHub.ScalarCodecs.Uri) GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData
teamResourcePath =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "teamResourcePath" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)


{-| The HTTP URL for this team
-}
teamUrl : SelectionSet (Maybe GitHub.ScalarCodecs.Uri) GitHub.Object.OrgRestoreMemberMembershipTeamAuditEntryData
teamUrl =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "teamUrl" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)
