-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.RegistryPackageDependency exposing (..)

import GitHub.Enum.RegistryPackageDependencyType
import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the type of dependency.
-}
dependencyType : SelectionSet GitHub.Enum.RegistryPackageDependencyType.RegistryPackageDependencyType GitHub.Object.RegistryPackageDependency
dependencyType =
    Object.selectionForField "Enum.RegistryPackageDependencyType.RegistryPackageDependencyType" "dependencyType" [] GitHub.Enum.RegistryPackageDependencyType.decoder


id : SelectionSet GitHub.ScalarCodecs.Id GitHub.Object.RegistryPackageDependency
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Identifies the name of the dependency.
-}
name : SelectionSet String GitHub.Object.RegistryPackageDependency
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| Identifies the version of the dependency.
-}
version : SelectionSet String GitHub.Object.RegistryPackageDependency
version =
    Object.selectionForField "String" "version" [] Decode.string
