-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.ReviewStatusHovercardContext exposing (..)

import GitHub.Enum.PullRequestReviewDecision
import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A string describing this context
-}
message : SelectionSet String GitHub.Object.ReviewStatusHovercardContext
message =
    Object.selectionForField "String" "message" [] Decode.string


{-| An octicon to accompany this context
-}
octicon : SelectionSet String GitHub.Object.ReviewStatusHovercardContext
octicon =
    Object.selectionForField "String" "octicon" [] Decode.string


{-| The current status of the pull request with respect to code review.
-}
reviewDecision : SelectionSet (Maybe GitHub.Enum.PullRequestReviewDecision.PullRequestReviewDecision) GitHub.Object.ReviewStatusHovercardContext
reviewDecision =
    Object.selectionForField "(Maybe Enum.PullRequestReviewDecision.PullRequestReviewDecision)" "reviewDecision" [] (GitHub.Enum.PullRequestReviewDecision.decoder |> Decode.nullable)
