-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.SearchResultItemConnection exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of pieces of code that matched the search query.
-}
codeCount : SelectionSet Int GitHub.Object.SearchResultItemConnection
codeCount =
    Object.selectionForField "Int" "codeCount" [] Decode.int


{-| A list of edges.
-}
edges : SelectionSet decodesTo GitHub.Object.SearchResultItemEdge -> SelectionSet (Maybe (List (Maybe decodesTo))) GitHub.Object.SearchResultItemConnection
edges object_ =
    Object.selectionForCompositeField "edges" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The number of issues that matched the search query.
-}
issueCount : SelectionSet Int GitHub.Object.SearchResultItemConnection
issueCount =
    Object.selectionForField "Int" "issueCount" [] Decode.int


{-| A list of nodes.
-}
nodes : SelectionSet decodesTo GitHub.Union.SearchResultItem -> SelectionSet (Maybe (List (Maybe decodesTo))) GitHub.Object.SearchResultItemConnection
nodes object_ =
    Object.selectionForCompositeField "nodes" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Information to aid in pagination.
-}
pageInfo : SelectionSet decodesTo GitHub.Object.PageInfo -> SelectionSet decodesTo GitHub.Object.SearchResultItemConnection
pageInfo object_ =
    Object.selectionForCompositeField "pageInfo" [] object_ identity


{-| The number of repositories that matched the search query.
-}
repositoryCount : SelectionSet Int GitHub.Object.SearchResultItemConnection
repositoryCount =
    Object.selectionForField "Int" "repositoryCount" [] Decode.int


{-| The number of users that matched the search query.
-}
userCount : SelectionSet Int GitHub.Object.SearchResultItemConnection
userCount =
    Object.selectionForField "Int" "userCount" [] Decode.int


{-| The number of wiki pages that matched the search query.
-}
wikiCount : SelectionSet Int GitHub.Object.SearchResultItemConnection
wikiCount =
    Object.selectionForField "Int" "wikiCount" [] Decode.int
