-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.Status exposing (..)

import GitHub.Enum.StatusState
import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The commit this status is attached to.
-}
commit : SelectionSet decodesTo GitHub.Object.Commit -> SelectionSet (Maybe decodesTo) GitHub.Object.Status
commit object_ =
    Object.selectionForCompositeField "commit" [] object_ (identity >> Decode.nullable)


type alias ContextRequiredArguments =
    { name : String }


{-| Looks up an individual status context by context name.

  - name - The context name.

-}
context : ContextRequiredArguments -> SelectionSet decodesTo GitHub.Object.StatusContext -> SelectionSet (Maybe decodesTo) GitHub.Object.Status
context requiredArgs object_ =
    Object.selectionForCompositeField "context" [ Argument.required "name" requiredArgs.name Encode.string ] object_ (identity >> Decode.nullable)


{-| The individual status contexts for this commit.
-}
contexts : SelectionSet decodesTo GitHub.Object.StatusContext -> SelectionSet (List decodesTo) GitHub.Object.Status
contexts object_ =
    Object.selectionForCompositeField "contexts" [] object_ (identity >> Decode.list)


id : SelectionSet GitHub.ScalarCodecs.Id GitHub.Object.Status
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The combined commit status.
-}
state : SelectionSet GitHub.Enum.StatusState.StatusState GitHub.Object.Status
state =
    Object.selectionForField "Enum.StatusState.StatusState" "state" [] GitHub.Enum.StatusState.decoder
