-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Interface.Node exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onAddedToProjectEvent : SelectionSet decodesTo GitHub.Object.AddedToProjectEvent
    , onApp : SelectionSet decodesTo GitHub.Object.App
    , onAssignedEvent : SelectionSet decodesTo GitHub.Object.AssignedEvent
    , onAutomaticBaseChangeFailedEvent : SelectionSet decodesTo GitHub.Object.AutomaticBaseChangeFailedEvent
    , onAutomaticBaseChangeSucceededEvent : SelectionSet decodesTo GitHub.Object.AutomaticBaseChangeSucceededEvent
    , onBaseRefChangedEvent : SelectionSet decodesTo GitHub.Object.BaseRefChangedEvent
    , onBaseRefForcePushedEvent : SelectionSet decodesTo GitHub.Object.BaseRefForcePushedEvent
    , onBlob : SelectionSet decodesTo GitHub.Object.Blob
    , onBot : SelectionSet decodesTo GitHub.Object.Bot
    , onBranchProtectionRule : SelectionSet decodesTo GitHub.Object.BranchProtectionRule
    , onClosedEvent : SelectionSet decodesTo GitHub.Object.ClosedEvent
    , onCodeOfConduct : SelectionSet decodesTo GitHub.Object.CodeOfConduct
    , onCommentDeletedEvent : SelectionSet decodesTo GitHub.Object.CommentDeletedEvent
    , onCommit : SelectionSet decodesTo GitHub.Object.Commit
    , onCommitComment : SelectionSet decodesTo GitHub.Object.CommitComment
    , onCommitCommentThread : SelectionSet decodesTo GitHub.Object.CommitCommentThread
    , onConnectedEvent : SelectionSet decodesTo GitHub.Object.ConnectedEvent
    , onConvertToDraftEvent : SelectionSet decodesTo GitHub.Object.ConvertToDraftEvent
    , onConvertedNoteToIssueEvent : SelectionSet decodesTo GitHub.Object.ConvertedNoteToIssueEvent
    , onCrossReferencedEvent : SelectionSet decodesTo GitHub.Object.CrossReferencedEvent
    , onDemilestonedEvent : SelectionSet decodesTo GitHub.Object.DemilestonedEvent
    , onDeployKey : SelectionSet decodesTo GitHub.Object.DeployKey
    , onDeployedEvent : SelectionSet decodesTo GitHub.Object.DeployedEvent
    , onDeployment : SelectionSet decodesTo GitHub.Object.Deployment
    , onDeploymentEnvironmentChangedEvent : SelectionSet decodesTo GitHub.Object.DeploymentEnvironmentChangedEvent
    , onDeploymentStatus : SelectionSet decodesTo GitHub.Object.DeploymentStatus
    , onDisconnectedEvent : SelectionSet decodesTo GitHub.Object.DisconnectedEvent
    , onEnterprise : SelectionSet decodesTo GitHub.Object.Enterprise
    , onEnterpriseAdministratorInvitation : SelectionSet decodesTo GitHub.Object.EnterpriseAdministratorInvitation
    , onEnterpriseIdentityProvider : SelectionSet decodesTo GitHub.Object.EnterpriseIdentityProvider
    , onEnterpriseRepositoryInfo : SelectionSet decodesTo GitHub.Object.EnterpriseRepositoryInfo
    , onEnterpriseServerInstallation : SelectionSet decodesTo GitHub.Object.EnterpriseServerInstallation
    , onEnterpriseServerUserAccount : SelectionSet decodesTo GitHub.Object.EnterpriseServerUserAccount
    , onEnterpriseServerUserAccountEmail : SelectionSet decodesTo GitHub.Object.EnterpriseServerUserAccountEmail
    , onEnterpriseServerUserAccountsUpload : SelectionSet decodesTo GitHub.Object.EnterpriseServerUserAccountsUpload
    , onEnterpriseUserAccount : SelectionSet decodesTo GitHub.Object.EnterpriseUserAccount
    , onExternalIdentity : SelectionSet decodesTo GitHub.Object.ExternalIdentity
    , onGist : SelectionSet decodesTo GitHub.Object.Gist
    , onGistComment : SelectionSet decodesTo GitHub.Object.GistComment
    , onHeadRefDeletedEvent : SelectionSet decodesTo GitHub.Object.HeadRefDeletedEvent
    , onHeadRefForcePushedEvent : SelectionSet decodesTo GitHub.Object.HeadRefForcePushedEvent
    , onHeadRefRestoredEvent : SelectionSet decodesTo GitHub.Object.HeadRefRestoredEvent
    , onIpAllowListEntry : SelectionSet decodesTo GitHub.Object.IpAllowListEntry
    , onIssue : SelectionSet decodesTo GitHub.Object.Issue
    , onIssueComment : SelectionSet decodesTo GitHub.Object.IssueComment
    , onLabel : SelectionSet decodesTo GitHub.Object.Label
    , onLabeledEvent : SelectionSet decodesTo GitHub.Object.LabeledEvent
    , onLanguage : SelectionSet decodesTo GitHub.Object.Language
    , onLicense : SelectionSet decodesTo GitHub.Object.License
    , onLockedEvent : SelectionSet decodesTo GitHub.Object.LockedEvent
    , onMannequin : SelectionSet decodesTo GitHub.Object.Mannequin
    , onMarkedAsDuplicateEvent : SelectionSet decodesTo GitHub.Object.MarkedAsDuplicateEvent
    , onMarketplaceCategory : SelectionSet decodesTo GitHub.Object.MarketplaceCategory
    , onMarketplaceListing : SelectionSet decodesTo GitHub.Object.MarketplaceListing
    , onMembersCanDeleteReposClearAuditEntry : SelectionSet decodesTo GitHub.Object.MembersCanDeleteReposClearAuditEntry
    , onMembersCanDeleteReposDisableAuditEntry : SelectionSet decodesTo GitHub.Object.MembersCanDeleteReposDisableAuditEntry
    , onMembersCanDeleteReposEnableAuditEntry : SelectionSet decodesTo GitHub.Object.MembersCanDeleteReposEnableAuditEntry
    , onMentionedEvent : SelectionSet decodesTo GitHub.Object.MentionedEvent
    , onMergedEvent : SelectionSet decodesTo GitHub.Object.MergedEvent
    , onMilestone : SelectionSet decodesTo GitHub.Object.Milestone
    , onMilestonedEvent : SelectionSet decodesTo GitHub.Object.MilestonedEvent
    , onMovedColumnsInProjectEvent : SelectionSet decodesTo GitHub.Object.MovedColumnsInProjectEvent
    , onOauthApplicationCreateAuditEntry : SelectionSet decodesTo GitHub.Object.OauthApplicationCreateAuditEntry
    , onOrgAddBillingManagerAuditEntry : SelectionSet decodesTo GitHub.Object.OrgAddBillingManagerAuditEntry
    , onOrgAddMemberAuditEntry : SelectionSet decodesTo GitHub.Object.OrgAddMemberAuditEntry
    , onOrgBlockUserAuditEntry : SelectionSet decodesTo GitHub.Object.OrgBlockUserAuditEntry
    , onOrgConfigDisableCollaboratorsOnlyAuditEntry : SelectionSet decodesTo GitHub.Object.OrgConfigDisableCollaboratorsOnlyAuditEntry
    , onOrgConfigEnableCollaboratorsOnlyAuditEntry : SelectionSet decodesTo GitHub.Object.OrgConfigEnableCollaboratorsOnlyAuditEntry
    , onOrgCreateAuditEntry : SelectionSet decodesTo GitHub.Object.OrgCreateAuditEntry
    , onOrgDisableOauthAppRestrictionsAuditEntry : SelectionSet decodesTo GitHub.Object.OrgDisableOauthAppRestrictionsAuditEntry
    , onOrgDisableSamlAuditEntry : SelectionSet decodesTo GitHub.Object.OrgDisableSamlAuditEntry
    , onOrgDisableTwoFactorRequirementAuditEntry : SelectionSet decodesTo GitHub.Object.OrgDisableTwoFactorRequirementAuditEntry
    , onOrgEnableOauthAppRestrictionsAuditEntry : SelectionSet decodesTo GitHub.Object.OrgEnableOauthAppRestrictionsAuditEntry
    , onOrgEnableSamlAuditEntry : SelectionSet decodesTo GitHub.Object.OrgEnableSamlAuditEntry
    , onOrgEnableTwoFactorRequirementAuditEntry : SelectionSet decodesTo GitHub.Object.OrgEnableTwoFactorRequirementAuditEntry
    , onOrgInviteMemberAuditEntry : SelectionSet decodesTo GitHub.Object.OrgInviteMemberAuditEntry
    , onOrgInviteToBusinessAuditEntry : SelectionSet decodesTo GitHub.Object.OrgInviteToBusinessAuditEntry
    , onOrgOauthAppAccessApprovedAuditEntry : SelectionSet decodesTo GitHub.Object.OrgOauthAppAccessApprovedAuditEntry
    , onOrgOauthAppAccessDeniedAuditEntry : SelectionSet decodesTo GitHub.Object.OrgOauthAppAccessDeniedAuditEntry
    , onOrgOauthAppAccessRequestedAuditEntry : SelectionSet decodesTo GitHub.Object.OrgOauthAppAccessRequestedAuditEntry
    , onOrgRemoveBillingManagerAuditEntry : SelectionSet decodesTo GitHub.Object.OrgRemoveBillingManagerAuditEntry
    , onOrgRemoveMemberAuditEntry : SelectionSet decodesTo GitHub.Object.OrgRemoveMemberAuditEntry
    , onOrgRemoveOutsideCollaboratorAuditEntry : SelectionSet decodesTo GitHub.Object.OrgRemoveOutsideCollaboratorAuditEntry
    , onOrgRestoreMemberAuditEntry : SelectionSet decodesTo GitHub.Object.OrgRestoreMemberAuditEntry
    , onOrgUnblockUserAuditEntry : SelectionSet decodesTo GitHub.Object.OrgUnblockUserAuditEntry
    , onOrgUpdateDefaultRepositoryPermissionAuditEntry : SelectionSet decodesTo GitHub.Object.OrgUpdateDefaultRepositoryPermissionAuditEntry
    , onOrgUpdateMemberAuditEntry : SelectionSet decodesTo GitHub.Object.OrgUpdateMemberAuditEntry
    , onOrgUpdateMemberRepositoryCreationPermissionAuditEntry : SelectionSet decodesTo GitHub.Object.OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    , onOrgUpdateMemberRepositoryInvitationPermissionAuditEntry : SelectionSet decodesTo GitHub.Object.OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    , onOrganization : SelectionSet decodesTo GitHub.Object.Organization
    , onOrganizationIdentityProvider : SelectionSet decodesTo GitHub.Object.OrganizationIdentityProvider
    , onOrganizationInvitation : SelectionSet decodesTo GitHub.Object.OrganizationInvitation
    , onPinnedEvent : SelectionSet decodesTo GitHub.Object.PinnedEvent
    , onPrivateRepositoryForkingDisableAuditEntry : SelectionSet decodesTo GitHub.Object.PrivateRepositoryForkingDisableAuditEntry
    , onPrivateRepositoryForkingEnableAuditEntry : SelectionSet decodesTo GitHub.Object.PrivateRepositoryForkingEnableAuditEntry
    , onProject : SelectionSet decodesTo GitHub.Object.Project
    , onProjectCard : SelectionSet decodesTo GitHub.Object.ProjectCard
    , onProjectColumn : SelectionSet decodesTo GitHub.Object.ProjectColumn
    , onPublicKey : SelectionSet decodesTo GitHub.Object.PublicKey
    , onPullRequest : SelectionSet decodesTo GitHub.Object.PullRequest
    , onPullRequestCommit : SelectionSet decodesTo GitHub.Object.PullRequestCommit
    , onPullRequestCommitCommentThread : SelectionSet decodesTo GitHub.Object.PullRequestCommitCommentThread
    , onPullRequestReview : SelectionSet decodesTo GitHub.Object.PullRequestReview
    , onPullRequestReviewComment : SelectionSet decodesTo GitHub.Object.PullRequestReviewComment
    , onPullRequestReviewThread : SelectionSet decodesTo GitHub.Object.PullRequestReviewThread
    , onPushAllowance : SelectionSet decodesTo GitHub.Object.PushAllowance
    , onReaction : SelectionSet decodesTo GitHub.Object.Reaction
    , onReadyForReviewEvent : SelectionSet decodesTo GitHub.Object.ReadyForReviewEvent
    , onRef : SelectionSet decodesTo GitHub.Object.Ref
    , onReferencedEvent : SelectionSet decodesTo GitHub.Object.ReferencedEvent
    , onRegistryPackage : SelectionSet decodesTo GitHub.Object.RegistryPackage
    , onRegistryPackageDependency : SelectionSet decodesTo GitHub.Object.RegistryPackageDependency
    , onRegistryPackageFile : SelectionSet decodesTo GitHub.Object.RegistryPackageFile
    , onRegistryPackageTag : SelectionSet decodesTo GitHub.Object.RegistryPackageTag
    , onRegistryPackageVersion : SelectionSet decodesTo GitHub.Object.RegistryPackageVersion
    , onRelease : SelectionSet decodesTo GitHub.Object.Release
    , onReleaseAsset : SelectionSet decodesTo GitHub.Object.ReleaseAsset
    , onRemovedFromProjectEvent : SelectionSet decodesTo GitHub.Object.RemovedFromProjectEvent
    , onRenamedTitleEvent : SelectionSet decodesTo GitHub.Object.RenamedTitleEvent
    , onReopenedEvent : SelectionSet decodesTo GitHub.Object.ReopenedEvent
    , onRepoAccessAuditEntry : SelectionSet decodesTo GitHub.Object.RepoAccessAuditEntry
    , onRepoAddMemberAuditEntry : SelectionSet decodesTo GitHub.Object.RepoAddMemberAuditEntry
    , onRepoAddTopicAuditEntry : SelectionSet decodesTo GitHub.Object.RepoAddTopicAuditEntry
    , onRepoArchivedAuditEntry : SelectionSet decodesTo GitHub.Object.RepoArchivedAuditEntry
    , onRepoChangeMergeSettingAuditEntry : SelectionSet decodesTo GitHub.Object.RepoChangeMergeSettingAuditEntry
    , onRepoConfigDisableAnonymousGitAccessAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigDisableAnonymousGitAccessAuditEntry
    , onRepoConfigDisableCollaboratorsOnlyAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigDisableCollaboratorsOnlyAuditEntry
    , onRepoConfigDisableContributorsOnlyAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigDisableContributorsOnlyAuditEntry
    , onRepoConfigDisableSockpuppetDisallowedAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigDisableSockpuppetDisallowedAuditEntry
    , onRepoConfigEnableAnonymousGitAccessAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigEnableAnonymousGitAccessAuditEntry
    , onRepoConfigEnableCollaboratorsOnlyAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigEnableCollaboratorsOnlyAuditEntry
    , onRepoConfigEnableContributorsOnlyAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigEnableContributorsOnlyAuditEntry
    , onRepoConfigEnableSockpuppetDisallowedAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigEnableSockpuppetDisallowedAuditEntry
    , onRepoConfigLockAnonymousGitAccessAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigLockAnonymousGitAccessAuditEntry
    , onRepoConfigUnlockAnonymousGitAccessAuditEntry : SelectionSet decodesTo GitHub.Object.RepoConfigUnlockAnonymousGitAccessAuditEntry
    , onRepoCreateAuditEntry : SelectionSet decodesTo GitHub.Object.RepoCreateAuditEntry
    , onRepoDestroyAuditEntry : SelectionSet decodesTo GitHub.Object.RepoDestroyAuditEntry
    , onRepoRemoveMemberAuditEntry : SelectionSet decodesTo GitHub.Object.RepoRemoveMemberAuditEntry
    , onRepoRemoveTopicAuditEntry : SelectionSet decodesTo GitHub.Object.RepoRemoveTopicAuditEntry
    , onRepository : SelectionSet decodesTo GitHub.Object.Repository
    , onRepositoryInvitation : SelectionSet decodesTo GitHub.Object.RepositoryInvitation
    , onRepositoryTopic : SelectionSet decodesTo GitHub.Object.RepositoryTopic
    , onRepositoryVisibilityChangeDisableAuditEntry : SelectionSet decodesTo GitHub.Object.RepositoryVisibilityChangeDisableAuditEntry
    , onRepositoryVisibilityChangeEnableAuditEntry : SelectionSet decodesTo GitHub.Object.RepositoryVisibilityChangeEnableAuditEntry
    , onRepositoryVulnerabilityAlert : SelectionSet decodesTo GitHub.Object.RepositoryVulnerabilityAlert
    , onReviewDismissalAllowance : SelectionSet decodesTo GitHub.Object.ReviewDismissalAllowance
    , onReviewDismissedEvent : SelectionSet decodesTo GitHub.Object.ReviewDismissedEvent
    , onReviewRequest : SelectionSet decodesTo GitHub.Object.ReviewRequest
    , onReviewRequestRemovedEvent : SelectionSet decodesTo GitHub.Object.ReviewRequestRemovedEvent
    , onReviewRequestedEvent : SelectionSet decodesTo GitHub.Object.ReviewRequestedEvent
    , onSavedReply : SelectionSet decodesTo GitHub.Object.SavedReply
    , onSecurityAdvisory : SelectionSet decodesTo GitHub.Object.SecurityAdvisory
    , onSponsorsListing : SelectionSet decodesTo GitHub.Object.SponsorsListing
    , onSponsorsTier : SelectionSet decodesTo GitHub.Object.SponsorsTier
    , onSponsorship : SelectionSet decodesTo GitHub.Object.Sponsorship
    , onStatus : SelectionSet decodesTo GitHub.Object.Status
    , onStatusCheckRollup : SelectionSet decodesTo GitHub.Object.StatusCheckRollup
    , onStatusContext : SelectionSet decodesTo GitHub.Object.StatusContext
    , onSubscribedEvent : SelectionSet decodesTo GitHub.Object.SubscribedEvent
    , onTag : SelectionSet decodesTo GitHub.Object.Tag
    , onTeam : SelectionSet decodesTo GitHub.Object.Team
    , onTeamAddMemberAuditEntry : SelectionSet decodesTo GitHub.Object.TeamAddMemberAuditEntry
    , onTeamAddRepositoryAuditEntry : SelectionSet decodesTo GitHub.Object.TeamAddRepositoryAuditEntry
    , onTeamChangeParentTeamAuditEntry : SelectionSet decodesTo GitHub.Object.TeamChangeParentTeamAuditEntry
    , onTeamDiscussion : SelectionSet decodesTo GitHub.Object.TeamDiscussion
    , onTeamDiscussionComment : SelectionSet decodesTo GitHub.Object.TeamDiscussionComment
    , onTeamRemoveMemberAuditEntry : SelectionSet decodesTo GitHub.Object.TeamRemoveMemberAuditEntry
    , onTeamRemoveRepositoryAuditEntry : SelectionSet decodesTo GitHub.Object.TeamRemoveRepositoryAuditEntry
    , onTopic : SelectionSet decodesTo GitHub.Object.Topic
    , onTransferredEvent : SelectionSet decodesTo GitHub.Object.TransferredEvent
    , onTree : SelectionSet decodesTo GitHub.Object.Tree
    , onUnassignedEvent : SelectionSet decodesTo GitHub.Object.UnassignedEvent
    , onUnlabeledEvent : SelectionSet decodesTo GitHub.Object.UnlabeledEvent
    , onUnlockedEvent : SelectionSet decodesTo GitHub.Object.UnlockedEvent
    , onUnmarkedAsDuplicateEvent : SelectionSet decodesTo GitHub.Object.UnmarkedAsDuplicateEvent
    , onUnpinnedEvent : SelectionSet decodesTo GitHub.Object.UnpinnedEvent
    , onUnsubscribedEvent : SelectionSet decodesTo GitHub.Object.UnsubscribedEvent
    , onUser : SelectionSet decodesTo GitHub.Object.User
    , onUserBlockedEvent : SelectionSet decodesTo GitHub.Object.UserBlockedEvent
    , onUserContentEdit : SelectionSet decodesTo GitHub.Object.UserContentEdit
    , onUserStatus : SelectionSet decodesTo GitHub.Object.UserStatus
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo GitHub.Interface.Node
fragments selections =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "AddedToProjectEvent" selections.onAddedToProjectEvent
        , Object.buildFragment "App" selections.onApp
        , Object.buildFragment "AssignedEvent" selections.onAssignedEvent
        , Object.buildFragment "AutomaticBaseChangeFailedEvent" selections.onAutomaticBaseChangeFailedEvent
        , Object.buildFragment "AutomaticBaseChangeSucceededEvent" selections.onAutomaticBaseChangeSucceededEvent
        , Object.buildFragment "BaseRefChangedEvent" selections.onBaseRefChangedEvent
        , Object.buildFragment "BaseRefForcePushedEvent" selections.onBaseRefForcePushedEvent
        , Object.buildFragment "Blob" selections.onBlob
        , Object.buildFragment "Bot" selections.onBot
        , Object.buildFragment "BranchProtectionRule" selections.onBranchProtectionRule
        , Object.buildFragment "ClosedEvent" selections.onClosedEvent
        , Object.buildFragment "CodeOfConduct" selections.onCodeOfConduct
        , Object.buildFragment "CommentDeletedEvent" selections.onCommentDeletedEvent
        , Object.buildFragment "Commit" selections.onCommit
        , Object.buildFragment "CommitComment" selections.onCommitComment
        , Object.buildFragment "CommitCommentThread" selections.onCommitCommentThread
        , Object.buildFragment "ConnectedEvent" selections.onConnectedEvent
        , Object.buildFragment "ConvertToDraftEvent" selections.onConvertToDraftEvent
        , Object.buildFragment "ConvertedNoteToIssueEvent" selections.onConvertedNoteToIssueEvent
        , Object.buildFragment "CrossReferencedEvent" selections.onCrossReferencedEvent
        , Object.buildFragment "DemilestonedEvent" selections.onDemilestonedEvent
        , Object.buildFragment "DeployKey" selections.onDeployKey
        , Object.buildFragment "DeployedEvent" selections.onDeployedEvent
        , Object.buildFragment "Deployment" selections.onDeployment
        , Object.buildFragment "DeploymentEnvironmentChangedEvent" selections.onDeploymentEnvironmentChangedEvent
        , Object.buildFragment "DeploymentStatus" selections.onDeploymentStatus
        , Object.buildFragment "DisconnectedEvent" selections.onDisconnectedEvent
        , Object.buildFragment "Enterprise" selections.onEnterprise
        , Object.buildFragment "EnterpriseAdministratorInvitation" selections.onEnterpriseAdministratorInvitation
        , Object.buildFragment "EnterpriseIdentityProvider" selections.onEnterpriseIdentityProvider
        , Object.buildFragment "EnterpriseRepositoryInfo" selections.onEnterpriseRepositoryInfo
        , Object.buildFragment "EnterpriseServerInstallation" selections.onEnterpriseServerInstallation
        , Object.buildFragment "EnterpriseServerUserAccount" selections.onEnterpriseServerUserAccount
        , Object.buildFragment "EnterpriseServerUserAccountEmail" selections.onEnterpriseServerUserAccountEmail
        , Object.buildFragment "EnterpriseServerUserAccountsUpload" selections.onEnterpriseServerUserAccountsUpload
        , Object.buildFragment "EnterpriseUserAccount" selections.onEnterpriseUserAccount
        , Object.buildFragment "ExternalIdentity" selections.onExternalIdentity
        , Object.buildFragment "Gist" selections.onGist
        , Object.buildFragment "GistComment" selections.onGistComment
        , Object.buildFragment "HeadRefDeletedEvent" selections.onHeadRefDeletedEvent
        , Object.buildFragment "HeadRefForcePushedEvent" selections.onHeadRefForcePushedEvent
        , Object.buildFragment "HeadRefRestoredEvent" selections.onHeadRefRestoredEvent
        , Object.buildFragment "IpAllowListEntry" selections.onIpAllowListEntry
        , Object.buildFragment "Issue" selections.onIssue
        , Object.buildFragment "IssueComment" selections.onIssueComment
        , Object.buildFragment "Label" selections.onLabel
        , Object.buildFragment "LabeledEvent" selections.onLabeledEvent
        , Object.buildFragment "Language" selections.onLanguage
        , Object.buildFragment "License" selections.onLicense
        , Object.buildFragment "LockedEvent" selections.onLockedEvent
        , Object.buildFragment "Mannequin" selections.onMannequin
        , Object.buildFragment "MarkedAsDuplicateEvent" selections.onMarkedAsDuplicateEvent
        , Object.buildFragment "MarketplaceCategory" selections.onMarketplaceCategory
        , Object.buildFragment "MarketplaceListing" selections.onMarketplaceListing
        , Object.buildFragment "MembersCanDeleteReposClearAuditEntry" selections.onMembersCanDeleteReposClearAuditEntry
        , Object.buildFragment "MembersCanDeleteReposDisableAuditEntry" selections.onMembersCanDeleteReposDisableAuditEntry
        , Object.buildFragment "MembersCanDeleteReposEnableAuditEntry" selections.onMembersCanDeleteReposEnableAuditEntry
        , Object.buildFragment "MentionedEvent" selections.onMentionedEvent
        , Object.buildFragment "MergedEvent" selections.onMergedEvent
        , Object.buildFragment "Milestone" selections.onMilestone
        , Object.buildFragment "MilestonedEvent" selections.onMilestonedEvent
        , Object.buildFragment "MovedColumnsInProjectEvent" selections.onMovedColumnsInProjectEvent
        , Object.buildFragment "OauthApplicationCreateAuditEntry" selections.onOauthApplicationCreateAuditEntry
        , Object.buildFragment "OrgAddBillingManagerAuditEntry" selections.onOrgAddBillingManagerAuditEntry
        , Object.buildFragment "OrgAddMemberAuditEntry" selections.onOrgAddMemberAuditEntry
        , Object.buildFragment "OrgBlockUserAuditEntry" selections.onOrgBlockUserAuditEntry
        , Object.buildFragment "OrgConfigDisableCollaboratorsOnlyAuditEntry" selections.onOrgConfigDisableCollaboratorsOnlyAuditEntry
        , Object.buildFragment "OrgConfigEnableCollaboratorsOnlyAuditEntry" selections.onOrgConfigEnableCollaboratorsOnlyAuditEntry
        , Object.buildFragment "OrgCreateAuditEntry" selections.onOrgCreateAuditEntry
        , Object.buildFragment "OrgDisableOauthAppRestrictionsAuditEntry" selections.onOrgDisableOauthAppRestrictionsAuditEntry
        , Object.buildFragment "OrgDisableSamlAuditEntry" selections.onOrgDisableSamlAuditEntry
        , Object.buildFragment "OrgDisableTwoFactorRequirementAuditEntry" selections.onOrgDisableTwoFactorRequirementAuditEntry
        , Object.buildFragment "OrgEnableOauthAppRestrictionsAuditEntry" selections.onOrgEnableOauthAppRestrictionsAuditEntry
        , Object.buildFragment "OrgEnableSamlAuditEntry" selections.onOrgEnableSamlAuditEntry
        , Object.buildFragment "OrgEnableTwoFactorRequirementAuditEntry" selections.onOrgEnableTwoFactorRequirementAuditEntry
        , Object.buildFragment "OrgInviteMemberAuditEntry" selections.onOrgInviteMemberAuditEntry
        , Object.buildFragment "OrgInviteToBusinessAuditEntry" selections.onOrgInviteToBusinessAuditEntry
        , Object.buildFragment "OrgOauthAppAccessApprovedAuditEntry" selections.onOrgOauthAppAccessApprovedAuditEntry
        , Object.buildFragment "OrgOauthAppAccessDeniedAuditEntry" selections.onOrgOauthAppAccessDeniedAuditEntry
        , Object.buildFragment "OrgOauthAppAccessRequestedAuditEntry" selections.onOrgOauthAppAccessRequestedAuditEntry
        , Object.buildFragment "OrgRemoveBillingManagerAuditEntry" selections.onOrgRemoveBillingManagerAuditEntry
        , Object.buildFragment "OrgRemoveMemberAuditEntry" selections.onOrgRemoveMemberAuditEntry
        , Object.buildFragment "OrgRemoveOutsideCollaboratorAuditEntry" selections.onOrgRemoveOutsideCollaboratorAuditEntry
        , Object.buildFragment "OrgRestoreMemberAuditEntry" selections.onOrgRestoreMemberAuditEntry
        , Object.buildFragment "OrgUnblockUserAuditEntry" selections.onOrgUnblockUserAuditEntry
        , Object.buildFragment "OrgUpdateDefaultRepositoryPermissionAuditEntry" selections.onOrgUpdateDefaultRepositoryPermissionAuditEntry
        , Object.buildFragment "OrgUpdateMemberAuditEntry" selections.onOrgUpdateMemberAuditEntry
        , Object.buildFragment "OrgUpdateMemberRepositoryCreationPermissionAuditEntry" selections.onOrgUpdateMemberRepositoryCreationPermissionAuditEntry
        , Object.buildFragment "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry" selections.onOrgUpdateMemberRepositoryInvitationPermissionAuditEntry
        , Object.buildFragment "Organization" selections.onOrganization
        , Object.buildFragment "OrganizationIdentityProvider" selections.onOrganizationIdentityProvider
        , Object.buildFragment "OrganizationInvitation" selections.onOrganizationInvitation
        , Object.buildFragment "PinnedEvent" selections.onPinnedEvent
        , Object.buildFragment "PrivateRepositoryForkingDisableAuditEntry" selections.onPrivateRepositoryForkingDisableAuditEntry
        , Object.buildFragment "PrivateRepositoryForkingEnableAuditEntry" selections.onPrivateRepositoryForkingEnableAuditEntry
        , Object.buildFragment "Project" selections.onProject
        , Object.buildFragment "ProjectCard" selections.onProjectCard
        , Object.buildFragment "ProjectColumn" selections.onProjectColumn
        , Object.buildFragment "PublicKey" selections.onPublicKey
        , Object.buildFragment "PullRequest" selections.onPullRequest
        , Object.buildFragment "PullRequestCommit" selections.onPullRequestCommit
        , Object.buildFragment "PullRequestCommitCommentThread" selections.onPullRequestCommitCommentThread
        , Object.buildFragment "PullRequestReview" selections.onPullRequestReview
        , Object.buildFragment "PullRequestReviewComment" selections.onPullRequestReviewComment
        , Object.buildFragment "PullRequestReviewThread" selections.onPullRequestReviewThread
        , Object.buildFragment "PushAllowance" selections.onPushAllowance
        , Object.buildFragment "Reaction" selections.onReaction
        , Object.buildFragment "ReadyForReviewEvent" selections.onReadyForReviewEvent
        , Object.buildFragment "Ref" selections.onRef
        , Object.buildFragment "ReferencedEvent" selections.onReferencedEvent
        , Object.buildFragment "RegistryPackage" selections.onRegistryPackage
        , Object.buildFragment "RegistryPackageDependency" selections.onRegistryPackageDependency
        , Object.buildFragment "RegistryPackageFile" selections.onRegistryPackageFile
        , Object.buildFragment "RegistryPackageTag" selections.onRegistryPackageTag
        , Object.buildFragment "RegistryPackageVersion" selections.onRegistryPackageVersion
        , Object.buildFragment "Release" selections.onRelease
        , Object.buildFragment "ReleaseAsset" selections.onReleaseAsset
        , Object.buildFragment "RemovedFromProjectEvent" selections.onRemovedFromProjectEvent
        , Object.buildFragment "RenamedTitleEvent" selections.onRenamedTitleEvent
        , Object.buildFragment "ReopenedEvent" selections.onReopenedEvent
        , Object.buildFragment "RepoAccessAuditEntry" selections.onRepoAccessAuditEntry
        , Object.buildFragment "RepoAddMemberAuditEntry" selections.onRepoAddMemberAuditEntry
        , Object.buildFragment "RepoAddTopicAuditEntry" selections.onRepoAddTopicAuditEntry
        , Object.buildFragment "RepoArchivedAuditEntry" selections.onRepoArchivedAuditEntry
        , Object.buildFragment "RepoChangeMergeSettingAuditEntry" selections.onRepoChangeMergeSettingAuditEntry
        , Object.buildFragment "RepoConfigDisableAnonymousGitAccessAuditEntry" selections.onRepoConfigDisableAnonymousGitAccessAuditEntry
        , Object.buildFragment "RepoConfigDisableCollaboratorsOnlyAuditEntry" selections.onRepoConfigDisableCollaboratorsOnlyAuditEntry
        , Object.buildFragment "RepoConfigDisableContributorsOnlyAuditEntry" selections.onRepoConfigDisableContributorsOnlyAuditEntry
        , Object.buildFragment "RepoConfigDisableSockpuppetDisallowedAuditEntry" selections.onRepoConfigDisableSockpuppetDisallowedAuditEntry
        , Object.buildFragment "RepoConfigEnableAnonymousGitAccessAuditEntry" selections.onRepoConfigEnableAnonymousGitAccessAuditEntry
        , Object.buildFragment "RepoConfigEnableCollaboratorsOnlyAuditEntry" selections.onRepoConfigEnableCollaboratorsOnlyAuditEntry
        , Object.buildFragment "RepoConfigEnableContributorsOnlyAuditEntry" selections.onRepoConfigEnableContributorsOnlyAuditEntry
        , Object.buildFragment "RepoConfigEnableSockpuppetDisallowedAuditEntry" selections.onRepoConfigEnableSockpuppetDisallowedAuditEntry
        , Object.buildFragment "RepoConfigLockAnonymousGitAccessAuditEntry" selections.onRepoConfigLockAnonymousGitAccessAuditEntry
        , Object.buildFragment "RepoConfigUnlockAnonymousGitAccessAuditEntry" selections.onRepoConfigUnlockAnonymousGitAccessAuditEntry
        , Object.buildFragment "RepoCreateAuditEntry" selections.onRepoCreateAuditEntry
        , Object.buildFragment "RepoDestroyAuditEntry" selections.onRepoDestroyAuditEntry
        , Object.buildFragment "RepoRemoveMemberAuditEntry" selections.onRepoRemoveMemberAuditEntry
        , Object.buildFragment "RepoRemoveTopicAuditEntry" selections.onRepoRemoveTopicAuditEntry
        , Object.buildFragment "Repository" selections.onRepository
        , Object.buildFragment "RepositoryInvitation" selections.onRepositoryInvitation
        , Object.buildFragment "RepositoryTopic" selections.onRepositoryTopic
        , Object.buildFragment "RepositoryVisibilityChangeDisableAuditEntry" selections.onRepositoryVisibilityChangeDisableAuditEntry
        , Object.buildFragment "RepositoryVisibilityChangeEnableAuditEntry" selections.onRepositoryVisibilityChangeEnableAuditEntry
        , Object.buildFragment "RepositoryVulnerabilityAlert" selections.onRepositoryVulnerabilityAlert
        , Object.buildFragment "ReviewDismissalAllowance" selections.onReviewDismissalAllowance
        , Object.buildFragment "ReviewDismissedEvent" selections.onReviewDismissedEvent
        , Object.buildFragment "ReviewRequest" selections.onReviewRequest
        , Object.buildFragment "ReviewRequestRemovedEvent" selections.onReviewRequestRemovedEvent
        , Object.buildFragment "ReviewRequestedEvent" selections.onReviewRequestedEvent
        , Object.buildFragment "SavedReply" selections.onSavedReply
        , Object.buildFragment "SecurityAdvisory" selections.onSecurityAdvisory
        , Object.buildFragment "SponsorsListing" selections.onSponsorsListing
        , Object.buildFragment "SponsorsTier" selections.onSponsorsTier
        , Object.buildFragment "Sponsorship" selections.onSponsorship
        , Object.buildFragment "Status" selections.onStatus
        , Object.buildFragment "StatusCheckRollup" selections.onStatusCheckRollup
        , Object.buildFragment "StatusContext" selections.onStatusContext
        , Object.buildFragment "SubscribedEvent" selections.onSubscribedEvent
        , Object.buildFragment "Tag" selections.onTag
        , Object.buildFragment "Team" selections.onTeam
        , Object.buildFragment "TeamAddMemberAuditEntry" selections.onTeamAddMemberAuditEntry
        , Object.buildFragment "TeamAddRepositoryAuditEntry" selections.onTeamAddRepositoryAuditEntry
        , Object.buildFragment "TeamChangeParentTeamAuditEntry" selections.onTeamChangeParentTeamAuditEntry
        , Object.buildFragment "TeamDiscussion" selections.onTeamDiscussion
        , Object.buildFragment "TeamDiscussionComment" selections.onTeamDiscussionComment
        , Object.buildFragment "TeamRemoveMemberAuditEntry" selections.onTeamRemoveMemberAuditEntry
        , Object.buildFragment "TeamRemoveRepositoryAuditEntry" selections.onTeamRemoveRepositoryAuditEntry
        , Object.buildFragment "Topic" selections.onTopic
        , Object.buildFragment "TransferredEvent" selections.onTransferredEvent
        , Object.buildFragment "Tree" selections.onTree
        , Object.buildFragment "UnassignedEvent" selections.onUnassignedEvent
        , Object.buildFragment "UnlabeledEvent" selections.onUnlabeledEvent
        , Object.buildFragment "UnlockedEvent" selections.onUnlockedEvent
        , Object.buildFragment "UnmarkedAsDuplicateEvent" selections.onUnmarkedAsDuplicateEvent
        , Object.buildFragment "UnpinnedEvent" selections.onUnpinnedEvent
        , Object.buildFragment "UnsubscribedEvent" selections.onUnsubscribedEvent
        , Object.buildFragment "User" selections.onUser
        , Object.buildFragment "UserBlockedEvent" selections.onUserBlockedEvent
        , Object.buildFragment "UserContentEdit" selections.onUserContentEdit
        , Object.buildFragment "UserStatus" selections.onUserStatus
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onAddedToProjectEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onApp = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onAssignedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onAutomaticBaseChangeFailedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onAutomaticBaseChangeSucceededEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBaseRefChangedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBaseRefForcePushedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBlob = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBot = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onBranchProtectionRule = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onClosedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCodeOfConduct = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCommentDeletedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCommit = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCommitComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCommitCommentThread = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onConnectedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onConvertToDraftEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onConvertedNoteToIssueEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCrossReferencedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDemilestonedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDeployKey = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDeployedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDeployment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDeploymentEnvironmentChangedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDeploymentStatus = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onDisconnectedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterprise = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseAdministratorInvitation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseIdentityProvider = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseRepositoryInfo = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseServerInstallation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseServerUserAccount = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseServerUserAccountEmail = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseServerUserAccountsUpload = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onEnterpriseUserAccount = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onExternalIdentity = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onGist = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onGistComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onHeadRefDeletedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onHeadRefForcePushedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onHeadRefRestoredEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onIpAllowListEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onIssue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onIssueComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLabel = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLabeledEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLanguage = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLicense = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onLockedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMannequin = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMarkedAsDuplicateEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMarketplaceCategory = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMarketplaceListing = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMembersCanDeleteReposClearAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMembersCanDeleteReposDisableAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMembersCanDeleteReposEnableAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMentionedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMergedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMilestone = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMilestonedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMovedColumnsInProjectEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOauthApplicationCreateAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgAddBillingManagerAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgAddMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgBlockUserAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgConfigDisableCollaboratorsOnlyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgConfigEnableCollaboratorsOnlyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgCreateAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgDisableOauthAppRestrictionsAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgDisableSamlAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgDisableTwoFactorRequirementAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgEnableOauthAppRestrictionsAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgEnableSamlAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgEnableTwoFactorRequirementAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgInviteMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgInviteToBusinessAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgOauthAppAccessApprovedAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgOauthAppAccessDeniedAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgOauthAppAccessRequestedAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgRemoveBillingManagerAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgRemoveMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgRemoveOutsideCollaboratorAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgRestoreMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgUnblockUserAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgUpdateDefaultRepositoryPermissionAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgUpdateMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgUpdateMemberRepositoryCreationPermissionAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrgUpdateMemberRepositoryInvitationPermissionAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrganization = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrganizationIdentityProvider = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrganizationInvitation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPinnedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPrivateRepositoryForkingDisableAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPrivateRepositoryForkingEnableAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProject = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjectCard = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjectColumn = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPublicKey = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequest = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequestCommit = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequestCommitCommentThread = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequestReview = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequestReviewComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequestReviewThread = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPushAllowance = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReaction = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReadyForReviewEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRef = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReferencedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRegistryPackage = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRegistryPackageDependency = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRegistryPackageFile = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRegistryPackageTag = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRegistryPackageVersion = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRelease = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReleaseAsset = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRemovedFromProjectEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRenamedTitleEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReopenedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoAccessAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoAddMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoAddTopicAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoArchivedAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoChangeMergeSettingAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigDisableAnonymousGitAccessAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigDisableCollaboratorsOnlyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigDisableContributorsOnlyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigDisableSockpuppetDisallowedAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigEnableAnonymousGitAccessAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigEnableCollaboratorsOnlyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigEnableContributorsOnlyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigEnableSockpuppetDisallowedAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigLockAnonymousGitAccessAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoConfigUnlockAnonymousGitAccessAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoCreateAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoDestroyAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoRemoveMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepoRemoveTopicAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepository = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepositoryInvitation = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepositoryTopic = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepositoryVisibilityChangeDisableAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepositoryVisibilityChangeEnableAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepositoryVulnerabilityAlert = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReviewDismissalAllowance = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReviewDismissedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReviewRequest = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReviewRequestRemovedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReviewRequestedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSavedReply = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSecurityAdvisory = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSponsorsListing = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSponsorsTier = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSponsorship = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onStatus = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onStatusCheckRollup = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onStatusContext = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onSubscribedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTag = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeam = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamAddMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamAddRepositoryAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamChangeParentTeamAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamDiscussion = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamDiscussionComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamRemoveMemberAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamRemoveRepositoryAuditEntry = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTopic = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTransferredEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTree = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnassignedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnlabeledEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnlockedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnmarkedAsDuplicateEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnpinnedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUnsubscribedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUser = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUserBlockedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUserContentEdit = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUserStatus = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| ID of the object.
-}
id : SelectionSet GitHub.ScalarCodecs.Id GitHub.Interface.Node
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)
