-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Interface.UniformResourceLocatable exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onBot : SelectionSet decodesTo GitHub.Object.Bot
    , onClosedEvent : SelectionSet decodesTo GitHub.Object.ClosedEvent
    , onCommit : SelectionSet decodesTo GitHub.Object.Commit
    , onCrossReferencedEvent : SelectionSet decodesTo GitHub.Object.CrossReferencedEvent
    , onGist : SelectionSet decodesTo GitHub.Object.Gist
    , onIssue : SelectionSet decodesTo GitHub.Object.Issue
    , onMannequin : SelectionSet decodesTo GitHub.Object.Mannequin
    , onMergedEvent : SelectionSet decodesTo GitHub.Object.MergedEvent
    , onMilestone : SelectionSet decodesTo GitHub.Object.Milestone
    , onOrganization : SelectionSet decodesTo GitHub.Object.Organization
    , onPullRequest : SelectionSet decodesTo GitHub.Object.PullRequest
    , onPullRequestCommit : SelectionSet decodesTo GitHub.Object.PullRequestCommit
    , onReadyForReviewEvent : SelectionSet decodesTo GitHub.Object.ReadyForReviewEvent
    , onRelease : SelectionSet decodesTo GitHub.Object.Release
    , onRepository : SelectionSet decodesTo GitHub.Object.Repository
    , onRepositoryTopic : SelectionSet decodesTo GitHub.Object.RepositoryTopic
    , onReviewDismissedEvent : SelectionSet decodesTo GitHub.Object.ReviewDismissedEvent
    , onTeamDiscussion : SelectionSet decodesTo GitHub.Object.TeamDiscussion
    , onTeamDiscussionComment : SelectionSet decodesTo GitHub.Object.TeamDiscussionComment
    , onUser : SelectionSet decodesTo GitHub.Object.User
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo GitHub.Interface.UniformResourceLocatable
fragments selections =
    Object.exhuastiveFragmentSelection
        [ Object.buildFragment "Bot" selections.onBot
        , Object.buildFragment "ClosedEvent" selections.onClosedEvent
        , Object.buildFragment "Commit" selections.onCommit
        , Object.buildFragment "CrossReferencedEvent" selections.onCrossReferencedEvent
        , Object.buildFragment "Gist" selections.onGist
        , Object.buildFragment "Issue" selections.onIssue
        , Object.buildFragment "Mannequin" selections.onMannequin
        , Object.buildFragment "MergedEvent" selections.onMergedEvent
        , Object.buildFragment "Milestone" selections.onMilestone
        , Object.buildFragment "Organization" selections.onOrganization
        , Object.buildFragment "PullRequest" selections.onPullRequest
        , Object.buildFragment "PullRequestCommit" selections.onPullRequestCommit
        , Object.buildFragment "ReadyForReviewEvent" selections.onReadyForReviewEvent
        , Object.buildFragment "Release" selections.onRelease
        , Object.buildFragment "Repository" selections.onRepository
        , Object.buildFragment "RepositoryTopic" selections.onRepositoryTopic
        , Object.buildFragment "ReviewDismissedEvent" selections.onReviewDismissedEvent
        , Object.buildFragment "TeamDiscussion" selections.onTeamDiscussion
        , Object.buildFragment "TeamDiscussionComment" selections.onTeamDiscussionComment
        , Object.buildFragment "User" selections.onUser
        ]


{-| Can be used to create a non-exhuastive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onBot = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onClosedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCommit = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCrossReferencedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onGist = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onIssue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMannequin = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMergedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMilestone = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onOrganization = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequest = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPullRequestCommit = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReadyForReviewEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRelease = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepository = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRepositoryTopic = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onReviewDismissedEvent = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamDiscussion = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTeamDiscussionComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUser = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The HTML path to this resource.
-}
resourcePath : SelectionSet GitHub.ScalarCodecs.Uri GitHub.Interface.UniformResourceLocatable
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The URL to this resource.
-}
url : SelectionSet GitHub.ScalarCodecs.Uri GitHub.Interface.UniformResourceLocatable
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecUri |> .decoder)
