-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Enum.EnterpriseMembersCanCreateRepositoriesSettingValue exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The possible values for the enterprise members can create repositories setting.

  - NoPolicy - Organization administrators choose whether to allow members to create repositories.
  - All - Members will be able to create public and private repositories.
  - Public - Members will be able to create only public repositories.
  - Private - Members will be able to create only private repositories.
  - Disabled - Members will not be able to create public or private repositories.

-}
type EnterpriseMembersCanCreateRepositoriesSettingValue
    = NoPolicy
    | All
    | Public
    | Private
    | Disabled


list : List EnterpriseMembersCanCreateRepositoriesSettingValue
list =
    [ NoPolicy, All, Public, Private, Disabled ]


decoder : Decoder EnterpriseMembersCanCreateRepositoriesSettingValue
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NO_POLICY" ->
                        Decode.succeed NoPolicy

                    "ALL" ->
                        Decode.succeed All

                    "PUBLIC" ->
                        Decode.succeed Public

                    "PRIVATE" ->
                        Decode.succeed Private

                    "DISABLED" ->
                        Decode.succeed Disabled

                    _ ->
                        Decode.fail ("Invalid EnterpriseMembersCanCreateRepositoriesSettingValue type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : EnterpriseMembersCanCreateRepositoriesSettingValue -> String
toString enum =
    case enum of
        NoPolicy ->
            "NO_POLICY"

        All ->
            "ALL"

        Public ->
            "PUBLIC"

        Private ->
            "PRIVATE"

        Disabled ->
            "DISABLED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe EnterpriseMembersCanCreateRepositoriesSettingValue
fromString enumString =
    case enumString of
        "NO_POLICY" ->
            Just NoPolicy

        "ALL" ->
            Just All

        "PUBLIC" ->
            Just Public

        "PRIVATE" ->
            Just Private

        "DISABLED" ->
            Just Disabled

        _ ->
            Nothing
