-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Enum.IpAllowListEntryOrderField exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Properties by which IP allow list entry connections can be ordered.

  - CreatedAt - Order IP allow list entries by creation time.
  - AllowListValue - Order IP allow list entries by the allow list value.

-}
type IpAllowListEntryOrderField
    = CreatedAt
    | AllowListValue


list : List IpAllowListEntryOrderField
list =
    [ CreatedAt, AllowListValue ]


decoder : Decoder IpAllowListEntryOrderField
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREATED_AT" ->
                        Decode.succeed CreatedAt

                    "ALLOW_LIST_VALUE" ->
                        Decode.succeed AllowListValue

                    _ ->
                        Decode.fail ("Invalid IpAllowListEntryOrderField type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : IpAllowListEntryOrderField -> String
toString enum =
    case enum of
        CreatedAt ->
            "CREATED_AT"

        AllowListValue ->
            "ALLOW_LIST_VALUE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe IpAllowListEntryOrderField
fromString enumString =
    case enumString of
        "CREATED_AT" ->
            Just CreatedAt

        "ALLOW_LIST_VALUE" ->
            Just AllowListValue

        _ ->
            Nothing
