-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Enum.PullRequestTimelineItemsItemType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The possible item types found in a timeline.

  - PullRequestCommit - Represents a Git commit part of a pull request.
  - PullRequestCommitCommentThread - Represents a commit comment thread part of a pull request.
  - PullRequestReview - A review object for a given pull request.
  - PullRequestReviewThread - A threaded list of comments for a given pull request.
  - PullRequestRevisionMarker - Represents the latest point in the pull request timeline for which the viewer has seen the pull request's commits.
  - BaseRefChangedEvent - Represents a 'base\_ref\_changed' event on a given issue or pull request.
  - BaseRefForcePushedEvent - Represents a 'base\_ref\_force\_pushed' event on a given pull request.
  - DeployedEvent - Represents a 'deployed' event on a given pull request.
  - DeploymentEnvironmentChangedEvent - Represents a 'deployment\_environment\_changed' event on a given pull request.
  - HeadRefDeletedEvent - Represents a 'head\_ref\_deleted' event on a given pull request.
  - HeadRefForcePushedEvent - Represents a 'head\_ref\_force\_pushed' event on a given pull request.
  - HeadRefRestoredEvent - Represents a 'head\_ref\_restored' event on a given pull request.
  - MergedEvent - Represents a 'merged' event on a given pull request.
  - ReviewDismissedEvent - Represents a 'review\_dismissed' event on a given issue or pull request.
  - ReviewRequestedEvent - Represents an 'review\_requested' event on a given pull request.
  - ReviewRequestRemovedEvent - Represents an 'review\_request\_removed' event on a given pull request.
  - ReadyForReviewEvent - Represents a 'ready\_for\_review' event on a given pull request.
  - IssueComment - Represents a comment on an Issue.
  - CrossReferencedEvent - Represents a mention made by one issue or pull request to another.
  - AddedToProjectEvent - Represents a 'added\_to\_project' event on a given issue or pull request.
  - AssignedEvent - Represents an 'assigned' event on any assignable object.
  - ClosedEvent - Represents a 'closed' event on any `Closable`.
  - CommentDeletedEvent - Represents a 'comment\_deleted' event on a given issue or pull request.
  - ConvertedNoteToIssueEvent - Represents a 'converted\_note\_to\_issue' event on a given issue or pull request.
  - DemilestonedEvent - Represents a 'demilestoned' event on a given issue or pull request.
  - LabeledEvent - Represents a 'labeled' event on a given issue or pull request.
  - LockedEvent - Represents a 'locked' event on a given issue or pull request.
  - MarkedAsDuplicateEvent - Represents a 'marked\_as\_duplicate' event on a given issue or pull request.
  - MentionedEvent - Represents a 'mentioned' event on a given issue or pull request.
  - MilestonedEvent - Represents a 'milestoned' event on a given issue or pull request.
  - MovedColumnsInProjectEvent - Represents a 'moved\_columns\_in\_project' event on a given issue or pull request.
  - PinnedEvent - Represents a 'pinned' event on a given issue or pull request.
  - ReferencedEvent - Represents a 'referenced' event on a given `ReferencedSubject`.
  - RemovedFromProjectEvent - Represents a 'removed\_from\_project' event on a given issue or pull request.
  - RenamedTitleEvent - Represents a 'renamed' event on a given issue or pull request
  - ReopenedEvent - Represents a 'reopened' event on any `Closable`.
  - SubscribedEvent - Represents a 'subscribed' event on a given `Subscribable`.
  - TransferredEvent - Represents a 'transferred' event on a given issue or pull request.
  - UnassignedEvent - Represents an 'unassigned' event on any assignable object.
  - UnlabeledEvent - Represents an 'unlabeled' event on a given issue or pull request.
  - UnlockedEvent - Represents an 'unlocked' event on a given issue or pull request.
  - UserBlockedEvent - Represents a 'user\_blocked' event on a given user.
  - UnpinnedEvent - Represents an 'unpinned' event on a given issue or pull request.
  - UnsubscribedEvent - Represents an 'unsubscribed' event on a given `Subscribable`.

-}
type PullRequestTimelineItemsItemType
    = PullRequestCommit
    | PullRequestCommitCommentThread
    | PullRequestReview
    | PullRequestReviewThread
    | PullRequestRevisionMarker
    | BaseRefChangedEvent
    | BaseRefForcePushedEvent
    | DeployedEvent
    | DeploymentEnvironmentChangedEvent
    | HeadRefDeletedEvent
    | HeadRefForcePushedEvent
    | HeadRefRestoredEvent
    | MergedEvent
    | ReviewDismissedEvent
    | ReviewRequestedEvent
    | ReviewRequestRemovedEvent
    | ReadyForReviewEvent
    | IssueComment
    | CrossReferencedEvent
    | AddedToProjectEvent
    | AssignedEvent
    | ClosedEvent
    | CommentDeletedEvent
    | ConvertedNoteToIssueEvent
    | DemilestonedEvent
    | LabeledEvent
    | LockedEvent
    | MarkedAsDuplicateEvent
    | MentionedEvent
    | MilestonedEvent
    | MovedColumnsInProjectEvent
    | PinnedEvent
    | ReferencedEvent
    | RemovedFromProjectEvent
    | RenamedTitleEvent
    | ReopenedEvent
    | SubscribedEvent
    | TransferredEvent
    | UnassignedEvent
    | UnlabeledEvent
    | UnlockedEvent
    | UserBlockedEvent
    | UnpinnedEvent
    | UnsubscribedEvent


list : List PullRequestTimelineItemsItemType
list =
    [ PullRequestCommit, PullRequestCommitCommentThread, PullRequestReview, PullRequestReviewThread, PullRequestRevisionMarker, BaseRefChangedEvent, BaseRefForcePushedEvent, DeployedEvent, DeploymentEnvironmentChangedEvent, HeadRefDeletedEvent, HeadRefForcePushedEvent, HeadRefRestoredEvent, MergedEvent, ReviewDismissedEvent, ReviewRequestedEvent, ReviewRequestRemovedEvent, ReadyForReviewEvent, IssueComment, CrossReferencedEvent, AddedToProjectEvent, AssignedEvent, ClosedEvent, CommentDeletedEvent, ConvertedNoteToIssueEvent, DemilestonedEvent, LabeledEvent, LockedEvent, MarkedAsDuplicateEvent, MentionedEvent, MilestonedEvent, MovedColumnsInProjectEvent, PinnedEvent, ReferencedEvent, RemovedFromProjectEvent, RenamedTitleEvent, ReopenedEvent, SubscribedEvent, TransferredEvent, UnassignedEvent, UnlabeledEvent, UnlockedEvent, UserBlockedEvent, UnpinnedEvent, UnsubscribedEvent ]


decoder : Decoder PullRequestTimelineItemsItemType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PULL_REQUEST_COMMIT" ->
                        Decode.succeed PullRequestCommit

                    "PULL_REQUEST_COMMIT_COMMENT_THREAD" ->
                        Decode.succeed PullRequestCommitCommentThread

                    "PULL_REQUEST_REVIEW" ->
                        Decode.succeed PullRequestReview

                    "PULL_REQUEST_REVIEW_THREAD" ->
                        Decode.succeed PullRequestReviewThread

                    "PULL_REQUEST_REVISION_MARKER" ->
                        Decode.succeed PullRequestRevisionMarker

                    "BASE_REF_CHANGED_EVENT" ->
                        Decode.succeed BaseRefChangedEvent

                    "BASE_REF_FORCE_PUSHED_EVENT" ->
                        Decode.succeed BaseRefForcePushedEvent

                    "DEPLOYED_EVENT" ->
                        Decode.succeed DeployedEvent

                    "DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT" ->
                        Decode.succeed DeploymentEnvironmentChangedEvent

                    "HEAD_REF_DELETED_EVENT" ->
                        Decode.succeed HeadRefDeletedEvent

                    "HEAD_REF_FORCE_PUSHED_EVENT" ->
                        Decode.succeed HeadRefForcePushedEvent

                    "HEAD_REF_RESTORED_EVENT" ->
                        Decode.succeed HeadRefRestoredEvent

                    "MERGED_EVENT" ->
                        Decode.succeed MergedEvent

                    "REVIEW_DISMISSED_EVENT" ->
                        Decode.succeed ReviewDismissedEvent

                    "REVIEW_REQUESTED_EVENT" ->
                        Decode.succeed ReviewRequestedEvent

                    "REVIEW_REQUEST_REMOVED_EVENT" ->
                        Decode.succeed ReviewRequestRemovedEvent

                    "READY_FOR_REVIEW_EVENT" ->
                        Decode.succeed ReadyForReviewEvent

                    "ISSUE_COMMENT" ->
                        Decode.succeed IssueComment

                    "CROSS_REFERENCED_EVENT" ->
                        Decode.succeed CrossReferencedEvent

                    "ADDED_TO_PROJECT_EVENT" ->
                        Decode.succeed AddedToProjectEvent

                    "ASSIGNED_EVENT" ->
                        Decode.succeed AssignedEvent

                    "CLOSED_EVENT" ->
                        Decode.succeed ClosedEvent

                    "COMMENT_DELETED_EVENT" ->
                        Decode.succeed CommentDeletedEvent

                    "CONVERTED_NOTE_TO_ISSUE_EVENT" ->
                        Decode.succeed ConvertedNoteToIssueEvent

                    "DEMILESTONED_EVENT" ->
                        Decode.succeed DemilestonedEvent

                    "LABELED_EVENT" ->
                        Decode.succeed LabeledEvent

                    "LOCKED_EVENT" ->
                        Decode.succeed LockedEvent

                    "MARKED_AS_DUPLICATE_EVENT" ->
                        Decode.succeed MarkedAsDuplicateEvent

                    "MENTIONED_EVENT" ->
                        Decode.succeed MentionedEvent

                    "MILESTONED_EVENT" ->
                        Decode.succeed MilestonedEvent

                    "MOVED_COLUMNS_IN_PROJECT_EVENT" ->
                        Decode.succeed MovedColumnsInProjectEvent

                    "PINNED_EVENT" ->
                        Decode.succeed PinnedEvent

                    "REFERENCED_EVENT" ->
                        Decode.succeed ReferencedEvent

                    "REMOVED_FROM_PROJECT_EVENT" ->
                        Decode.succeed RemovedFromProjectEvent

                    "RENAMED_TITLE_EVENT" ->
                        Decode.succeed RenamedTitleEvent

                    "REOPENED_EVENT" ->
                        Decode.succeed ReopenedEvent

                    "SUBSCRIBED_EVENT" ->
                        Decode.succeed SubscribedEvent

                    "TRANSFERRED_EVENT" ->
                        Decode.succeed TransferredEvent

                    "UNASSIGNED_EVENT" ->
                        Decode.succeed UnassignedEvent

                    "UNLABELED_EVENT" ->
                        Decode.succeed UnlabeledEvent

                    "UNLOCKED_EVENT" ->
                        Decode.succeed UnlockedEvent

                    "USER_BLOCKED_EVENT" ->
                        Decode.succeed UserBlockedEvent

                    "UNPINNED_EVENT" ->
                        Decode.succeed UnpinnedEvent

                    "UNSUBSCRIBED_EVENT" ->
                        Decode.succeed UnsubscribedEvent

                    _ ->
                        Decode.fail ("Invalid PullRequestTimelineItemsItemType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PullRequestTimelineItemsItemType -> String
toString enum =
    case enum of
        PullRequestCommit ->
            "PULL_REQUEST_COMMIT"

        PullRequestCommitCommentThread ->
            "PULL_REQUEST_COMMIT_COMMENT_THREAD"

        PullRequestReview ->
            "PULL_REQUEST_REVIEW"

        PullRequestReviewThread ->
            "PULL_REQUEST_REVIEW_THREAD"

        PullRequestRevisionMarker ->
            "PULL_REQUEST_REVISION_MARKER"

        BaseRefChangedEvent ->
            "BASE_REF_CHANGED_EVENT"

        BaseRefForcePushedEvent ->
            "BASE_REF_FORCE_PUSHED_EVENT"

        DeployedEvent ->
            "DEPLOYED_EVENT"

        DeploymentEnvironmentChangedEvent ->
            "DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT"

        HeadRefDeletedEvent ->
            "HEAD_REF_DELETED_EVENT"

        HeadRefForcePushedEvent ->
            "HEAD_REF_FORCE_PUSHED_EVENT"

        HeadRefRestoredEvent ->
            "HEAD_REF_RESTORED_EVENT"

        MergedEvent ->
            "MERGED_EVENT"

        ReviewDismissedEvent ->
            "REVIEW_DISMISSED_EVENT"

        ReviewRequestedEvent ->
            "REVIEW_REQUESTED_EVENT"

        ReviewRequestRemovedEvent ->
            "REVIEW_REQUEST_REMOVED_EVENT"

        ReadyForReviewEvent ->
            "READY_FOR_REVIEW_EVENT"

        IssueComment ->
            "ISSUE_COMMENT"

        CrossReferencedEvent ->
            "CROSS_REFERENCED_EVENT"

        AddedToProjectEvent ->
            "ADDED_TO_PROJECT_EVENT"

        AssignedEvent ->
            "ASSIGNED_EVENT"

        ClosedEvent ->
            "CLOSED_EVENT"

        CommentDeletedEvent ->
            "COMMENT_DELETED_EVENT"

        ConvertedNoteToIssueEvent ->
            "CONVERTED_NOTE_TO_ISSUE_EVENT"

        DemilestonedEvent ->
            "DEMILESTONED_EVENT"

        LabeledEvent ->
            "LABELED_EVENT"

        LockedEvent ->
            "LOCKED_EVENT"

        MarkedAsDuplicateEvent ->
            "MARKED_AS_DUPLICATE_EVENT"

        MentionedEvent ->
            "MENTIONED_EVENT"

        MilestonedEvent ->
            "MILESTONED_EVENT"

        MovedColumnsInProjectEvent ->
            "MOVED_COLUMNS_IN_PROJECT_EVENT"

        PinnedEvent ->
            "PINNED_EVENT"

        ReferencedEvent ->
            "REFERENCED_EVENT"

        RemovedFromProjectEvent ->
            "REMOVED_FROM_PROJECT_EVENT"

        RenamedTitleEvent ->
            "RENAMED_TITLE_EVENT"

        ReopenedEvent ->
            "REOPENED_EVENT"

        SubscribedEvent ->
            "SUBSCRIBED_EVENT"

        TransferredEvent ->
            "TRANSFERRED_EVENT"

        UnassignedEvent ->
            "UNASSIGNED_EVENT"

        UnlabeledEvent ->
            "UNLABELED_EVENT"

        UnlockedEvent ->
            "UNLOCKED_EVENT"

        UserBlockedEvent ->
            "USER_BLOCKED_EVENT"

        UnpinnedEvent ->
            "UNPINNED_EVENT"

        UnsubscribedEvent ->
            "UNSUBSCRIBED_EVENT"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PullRequestTimelineItemsItemType
fromString enumString =
    case enumString of
        "PULL_REQUEST_COMMIT" ->
            Just PullRequestCommit

        "PULL_REQUEST_COMMIT_COMMENT_THREAD" ->
            Just PullRequestCommitCommentThread

        "PULL_REQUEST_REVIEW" ->
            Just PullRequestReview

        "PULL_REQUEST_REVIEW_THREAD" ->
            Just PullRequestReviewThread

        "PULL_REQUEST_REVISION_MARKER" ->
            Just PullRequestRevisionMarker

        "BASE_REF_CHANGED_EVENT" ->
            Just BaseRefChangedEvent

        "BASE_REF_FORCE_PUSHED_EVENT" ->
            Just BaseRefForcePushedEvent

        "DEPLOYED_EVENT" ->
            Just DeployedEvent

        "DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT" ->
            Just DeploymentEnvironmentChangedEvent

        "HEAD_REF_DELETED_EVENT" ->
            Just HeadRefDeletedEvent

        "HEAD_REF_FORCE_PUSHED_EVENT" ->
            Just HeadRefForcePushedEvent

        "HEAD_REF_RESTORED_EVENT" ->
            Just HeadRefRestoredEvent

        "MERGED_EVENT" ->
            Just MergedEvent

        "REVIEW_DISMISSED_EVENT" ->
            Just ReviewDismissedEvent

        "REVIEW_REQUESTED_EVENT" ->
            Just ReviewRequestedEvent

        "REVIEW_REQUEST_REMOVED_EVENT" ->
            Just ReviewRequestRemovedEvent

        "READY_FOR_REVIEW_EVENT" ->
            Just ReadyForReviewEvent

        "ISSUE_COMMENT" ->
            Just IssueComment

        "CROSS_REFERENCED_EVENT" ->
            Just CrossReferencedEvent

        "ADDED_TO_PROJECT_EVENT" ->
            Just AddedToProjectEvent

        "ASSIGNED_EVENT" ->
            Just AssignedEvent

        "CLOSED_EVENT" ->
            Just ClosedEvent

        "COMMENT_DELETED_EVENT" ->
            Just CommentDeletedEvent

        "CONVERTED_NOTE_TO_ISSUE_EVENT" ->
            Just ConvertedNoteToIssueEvent

        "DEMILESTONED_EVENT" ->
            Just DemilestonedEvent

        "LABELED_EVENT" ->
            Just LabeledEvent

        "LOCKED_EVENT" ->
            Just LockedEvent

        "MARKED_AS_DUPLICATE_EVENT" ->
            Just MarkedAsDuplicateEvent

        "MENTIONED_EVENT" ->
            Just MentionedEvent

        "MILESTONED_EVENT" ->
            Just MilestonedEvent

        "MOVED_COLUMNS_IN_PROJECT_EVENT" ->
            Just MovedColumnsInProjectEvent

        "PINNED_EVENT" ->
            Just PinnedEvent

        "REFERENCED_EVENT" ->
            Just ReferencedEvent

        "REMOVED_FROM_PROJECT_EVENT" ->
            Just RemovedFromProjectEvent

        "RENAMED_TITLE_EVENT" ->
            Just RenamedTitleEvent

        "REOPENED_EVENT" ->
            Just ReopenedEvent

        "SUBSCRIBED_EVENT" ->
            Just SubscribedEvent

        "TRANSFERRED_EVENT" ->
            Just TransferredEvent

        "UNASSIGNED_EVENT" ->
            Just UnassignedEvent

        "UNLABELED_EVENT" ->
            Just UnlabeledEvent

        "UNLOCKED_EVENT" ->
            Just UnlockedEvent

        "USER_BLOCKED_EVENT" ->
            Just UserBlockedEvent

        "UNPINNED_EVENT" ->
            Just UnpinnedEvent

        "UNSUBSCRIBED_EVENT" ->
            Just UnsubscribedEvent

        _ ->
            Nothing
